import { PrismaClient } from "@prisma/client";
import { config } from "dotenv";

config(); // Load environment variables

const prisma = new PrismaClient();

async function main() {
  // Create providers
  const anwardataco = await prisma.provider.findUnique({
    where: { name: "anwardataco" },
  });

  const alrahuzdata = await prisma.provider.findUnique({
    where: { name: "alrahuzdata" },
  });

  const dataplus = await prisma.provider.findUnique({
    where: { name: "dataplus" },
  });

  const ameentaccetelecom = await prisma.provider.findUnique({
    where: { name: "ameentaccetelecom" },
  });

  if (!anwardataco || !alrahuzdata || !dataplus || !ameentaccetelecom) {
    throw new Error("One or more providers not found");
  }

  // Add data plans for anwardataco
  await prisma.dataPlan.createMany({
    data: [
      {
        dataId: 367,
        network: "GLO",
        planType: "SME",
        amount: 1885,
        size: "10.0 GB",
        validity: "7days",
      },
      {
        dataId: 365,
        network: "GLO",
        planType: "SME",
        amount: 290,
        size: "1.5 GB",
        validity: "2days",
      },
      {
        dataId: 366,
        network: "GLO",
        planType: "SME",
        amount: 475,
        size: "2.5 GB",
        validity: "2days",
      },
      {
        dataId: 358,
        network: "MTN",
        planType: "GIFTING",
        amount: 785,
        size: "1.0 GB",
        validity: "7(DAYS) VALIDITY+25MIN",
      },
      {
        dataId: 359,
        network: "MTN",
        planType: "GIFTING",
        amount: 1465,
        size: "2.0 GB",
        validity: "30(DAYS) VALIDITY+ 2MIN",
      },
      {
        dataId: 360,
        network: "MTN",
        planType: "GIFTING",
        amount: 2450,
        size: "3.5 GB",
        validity: "30(DAYS) VALIDITY",
      },
      {
        dataId: 361,
        network: "MTN",
        planType: "GIFTING",
        amount: 3450,
        size: "7.0 GB",
        validity: "30(DAYS) VALIDITY+ 2gbnight",
      },
      {
        dataId: 313,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 4100,
        size: "10.0 GB",
        validity: "30days",
      },
      {
        dataId: 183,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 890,
        size: "1.5 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 184,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1060,
        size: "2.0 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 185,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1340,
        size: "3.0 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 186,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1770,
        size: "4.5 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 187,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 3540,
        size: "11.0 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 188,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 2550,
        size: "15.0 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 189,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 8840,
        size: "40.0 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 190,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 12330,
        size: "75.0 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 368,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 1500,
        size: "3.5 GB",
        validity: "7days",
      },
      {
        dataId: 369,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 985,
        size: "1.5 GB",
        validity: "7days",
      },
      {
        dataId: 375,
        network: "AIRTEL",
        planType: "SME",
        amount: 340,
        size: "1.0 GB",
        validity: "3DAYS (SOCIAL )",
      },
      {
        dataId: 387,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 960,
        size: "3.0 GB",
        validity: "7days",
      },
      {
        dataId: 388,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 1590,
        size: "5.0 GB",
        validity: "7days",
      },
      {
        dataId: 395,
        network: "AIRTEL",
        planType: "SME",
        amount: 1550,
        size: "3.5 GB",
        validity: "7days",
      },
      {
        dataId: 338,
        network: "MTN",
        planType: "GIFTING",
        amount: 3420,
        size: "11.0 GB",
        validity: "7days",
      },
      {
        dataId: 337,
        network: "MTN",
        planType: "GIFTING",
        amount: 20000,
        size: "75.0 GB",
        validity: "30days",
      },
      {
        dataId: 362,
        network: "MTN",
        planType: "GIFTING",
        amount: 500,
        size: "500.0 MB",
        validity: "7days",
      },
      {
        dataId: 363,
        network: "MTN",
        planType: "GIFTING",
        amount: 205,
        size: "230.0 MB",
        validity: "1day",
      },
      {
        dataId: 364,
        network: "GLO",
        planType: "SME",
        amount: 190,
        size: "750.0 MB",
        validity: "1day",
      },
      {
        dataId: 226,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 2960,
        size: "8.0 GB",
        validity: "30days",
      },
      {
        dataId: 228,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 500,
        size: "500.0 MB",
        validity: "7days",
      },
      {
        dataId: 229,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 790,
        size: "1.0 GB",
        validity: "7days",
      },
      {
        dataId: 230,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 1480,
        size: "2.0 GB",
        validity: "30days",
      },
      {
        dataId: 231,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 2000,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 238,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 2510,
        size: "4.0 GB",
        validity: "30days",
      },
      {
        dataId: 335,
        network: "MTN",
        planType: "GIFTING",
        amount: 2430,
        size: "6.0 GB",
        validity: "7days",
      },
      {
        dataId: 334,
        network: "MTN",
        planType: "GIFTING",
        amount: 1000,
        size: "3.2 GB",
        validity: "2days",
      },
      {
        dataId: 246,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 2250,
        size: "5.0 GB",
        validity: "30days",
      },
      {
        dataId: 247,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 225,
        size: "500.0 MB",
        validity: "14days",
      },
      {
        dataId: 248,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 900,
        size: "2.0 GB",
        validity: "30days",
      },
      {
        dataId: 249,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 90,
        size: "200.0 MB",
        validity: "14days",
      },
      {
        dataId: 250,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 450,
        size: "1.0 GB",
        validity: "30days",
      },
      {
        dataId: 251,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 4500,
        size: "10.0 GB",
        validity: "30days",
      },
      {
        dataId: 252,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 1350,
        size: "3.0 GB",
        validity: "30days",
      },
      {
        dataId: 271,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 300,
        size: "1.0 GB",
        validity: "30days",
      },
      {
        dataId: 256,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 120,
        size: "500.0 MB",
        validity: "30days Corporate gifting",
      },
      {
        dataId: 258,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 575,
        size: "2.0 GB",
        validity: "30days Corporate gifting",
      },
      {
        dataId: 259,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 450,
        size: "1.5 GB",
        validity: "30days",
      },
      {
        dataId: 260,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 850,
        size: "3.0 GB",
        validity: "30days",
      },
      {
        dataId: 261,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 1500,
        size: "5.0 GB",
        validity: "30days",
      },
      {
        dataId: 262,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 2850,
        size: "10.0 GB",
        validity: "30days",
      },
      {
        dataId: 270,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 1150,
        size: "4.0 GB",
        validity: "30days",
      },
      {
        dataId: 386,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 325,
        size: "1.0 GB",
        validity: "7days",
      },
      {
        dataId: 376,
        network: "MTN",
        planType: "SME",
        amount: 650,
        size: "1.0 GB",
        validity: "30days",
      },
      {
        dataId: 378,
        network: "MTN",
        planType: "SME",
        amount: 1400,
        size: "2.0 GB",
        validity: "30days",
      },
      {
        dataId: 379,
        network: "MTN",
        planType: "SME",
        amount: 1900,
        size: "3.0 GB",
        validity: "30days",
      },
      {
        dataId: 380,
        network: "MTN",
        planType: "SME",
        amount: 2900,
        size: "5.0 GB",
        validity: "30days",
      },
      {
        dataId: 384,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 815,
        size: "3.0 GB",
        validity: "3days",
      },
      {
        dataId: 385,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 1350,
        size: "5.0 GB",
        validity: "3days",
      },
      {
        dataId: 281,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 145,
        size: "500.0 MB",
        validity: "30days",
      },
      {
        dataId: 284,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 4200,
        size: "15.0 MB",
        validity: "30days",
      },
      {
        dataId: 333,
        network: "MTN",
        planType: "GIFTING",
        amount: 500,
        size: "1.0 GB",
        validity: "1day",
      },
      {
        dataId: 286,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 5600,
        size: "20.0 GB",
        validity: "30days",
      },
      {
        dataId: 339,
        network: "AIRTEL",
        planType: "SME",
        amount: 70,
        size: "150.0 MB",
        validity: "1day",
      },
      {
        dataId: 322,
        network: "AIRTEL",
        planType: "SME",
        amount: 3100,
        size: "10.0 GB",
        validity: "30days",
      },
      {
        dataId: 394,
        network: "AIRTEL",
        planType: "SME",
        amount: 115,
        size: "300.0 MB",
        validity: "2days",
      },
      {
        dataId: 393,
        network: "AIRTEL",
        planType: "SME",
        amount: 215,
        size: "600.0 MB",
        validity: "2days",
      },
      {
        dataId: 383,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 275,
        size: "1.0 GB",
        validity: "3days",
      },
      {
        dataId: 396,
        network: "MTN",
        planType: "SME",
        amount: 450,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 329,
        network: "AIRTEL",
        planType: "SME",
        amount: 2100,
        size: "7.0 GB",
        validity: "7days",
      },
    ].map((plan) => ({ ...plan, providerId: anwardataco.id })),
  });

  // Add data plans for alrahuzdata
  await prisma.dataPlan.createMany({
    data: [
      // 9MOBILE GIFTING
      {
        dataId: 182,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 425,
        size: "500.0 MB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 183,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 850,
        size: "1.5 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 184,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1020,
        size: "2.0 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 185,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1275,
        size: "3.0 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 186,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1700,
        size: "4.5 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 187,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 3400,
        size: "11.0 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 188,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 4200,
        size: "15.0 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 189,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 8500,
        size: "40.0 GB",
        validity: "30 days{Gifting}",
      },
      {
        dataId: 248,
        network: "9MOBILE",
        planType: "SME",
        amount: 220,
        size: "1.0 GB",
        validity: "1 month",
      },
      {
        dataId: 249,
        network: "9MOBILE",
        planType: "SME",
        amount: 330,
        size: "1.5 GB",
        validity: "1 month",
      },
      {
        dataId: 250,
        network: "9MOBILE",
        planType: "SME",
        amount: 440,
        size: "2.0 GB",
        validity: "1 month",
      },
      {
        dataId: 251,
        network: "9MOBILE",
        planType: "SME",
        amount: 660,
        size: "3.0 GB",
        validity: "1 month",
      },
      {
        dataId: 252,
        network: "9MOBILE",
        planType: "SME",
        amount: 880,
        size: "4.0 GB",
        validity: "1 month",
      },
      {
        dataId: 253,
        network: "9MOBILE",
        planType: "SME",
        amount: 1100,
        size: "5.0 GB",
        validity: "1 month",
      },
      {
        dataId: 262,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 12750,
        size: "75.0 GB",
        validity: "1 month",
      },
      {
        dataId: 269,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 46,
        size: "25.0 MB",
        validity: "1day",
      },
      {
        dataId: 270,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 175,
        size: "650.0 MB",
        validity: "1 day",
      },
      {
        dataId: 272,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 425,
        size: "2000.0 MB",
        validity: "3(2gb)days",
      },
      {
        dataId: 273,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1275,
        size: "7.0 GB",
        validity: "7days(weekly)",
      },
      {
        dataId: 292,
        network: "9MOBILE",
        planType: "SME",
        amount: 2200,
        size: "10.0 GB",
        validity: "30days",
      },
      {
        dataId: 296,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 278,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 297,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 556,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 298,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 417,
        size: "1.5 GB",
        validity: "30 days",
      },
      {
        dataId: 299,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 834,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 300,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 1390,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 301,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 2780,
        size: "10.0 GB",
        validity: "30 days",
      },
      {
        dataId: 302,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 139,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 303,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 1112,
        size: "4.0 GB",
        validity: "30 days",
      },
      {
        dataId: 304,
        network: "9MOBILE",
        planType: "SME",
        amount: 980,
        size: "4.5 GB",
        validity: "30 days",
      },
      {
        dataId: 305,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 30,
        size: "25.0 MB",
        validity: "30 days",
      },
      // ...continue for AIRTEL, GLO, MTN as needed, using the same format
      // AIRTEL
      {
        dataId: 425,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 2045,
        size: "7.0 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 426,
        network: "AIRTEL",
        planType: "SME",
        amount: 2045,
        size: "7.0 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 427,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 3040,
        size: "10.0 GB",
        validity: "30DAYS VALIDITY",
      },
      {
        dataId: 428,
        network: "AIRTEL",
        planType: "SME",
        amount: 3040,
        size: "10.0 GB",
        validity: "30DAYS VALIDITY",
      },
      {
        dataId: 436,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 65,
        size: "150.0 MB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 437,
        network: "AIRTEL",
        planType: "SME",
        amount: 60,
        size: "150.0 MB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 460,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 550,
        size: "2.0 GB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 461,
        network: "AIRTEL",
        planType: "SME",
        amount: 550,
        size: "2.0 GB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 483,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 320,
        size: "1.0 GB",
        validity: "3DAYS VALIDITY(social bundle)",
      },
      {
        dataId: 484,
        network: "AIRTEL",
        planType: "SME",
        amount: 320,
        size: "1.0 GB",
        validity: "3DAYS VALIDITY(social bundle)",
      },
      {
        dataId: 485,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 4980,
        size: "13.0 GB",
        validity: "MIFI 30DAYS VALIDITY",
      },
      {
        dataId: 486,
        network: "AIRTEL",
        planType: "SME",
        amount: 4980,
        size: "13.0 GB",
        validity: "MIFI 30DAYS VALIDITY",
      },
      {
        dataId: 487,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 9950,
        size: "35.0 GB",
        validity: "(MIFI) 30DAYS",
      },
      {
        dataId: 488,
        network: "AIRTEL",
        planType: "SME",
        amount: 9950,
        size: "35.0 GB",
        validity: "(MIFI) 30DAYS",
      },
      {
        dataId: 489,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 14900,
        size: "60.0 GB",
        validity: "(MIFI) 30DAYS",
      },
      {
        dataId: 490,
        network: "AIRTEL",
        planType: "SME",
        amount: 14900,
        size: "60.0 GB",
        validity: "(MIFI) 30DAYS",
      },
      // CORPORATE GIFTING (AIRTEL)
      {
        dataId: 515,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 493,
        size: "500.0 MB",
        validity: "7 days",
      },
      {
        dataId: 516,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 790,
        size: "1.0 GB",
        validity: "7 days",
      },
      {
        dataId: 517,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 1480,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 518,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 1960,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 519,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 2460,
        size: "4.0 GB",
        validity: "30 days",
      },
      {
        dataId: 520,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 2950,
        size: "8.0 GB",
        validity: "30 days",
      },
      {
        dataId: 521,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 3910,
        size: "10.0 GB",
        validity: "30 days",
      },
      {
        dataId: 522,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 4900,
        size: "13.0 GB",
        validity: "30 days",
      },
      {
        dataId: 523,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 5870,
        size: "18.0 GB",
        validity: "30 days",
      },
      {
        dataId: 524,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 7820,
        size: "25.0 GB",
        validity: "30 days",
      },
      {
        dataId: 525,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 75,
        size: "75.0 MB",
        validity: "1 Daily",
      },
      {
        dataId: 526,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 100,
        size: "100.0 MB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 527,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 200,
        size: "200.0 MB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 528,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 298,
        size: "300.0 MB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 529,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 9750,
        size: "35.0 GB",
        validity: "30 days",
      },
      {
        dataId: 530,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 14600,
        size: "60.0 GB",
        validity: "30 days",
      },
      // OTHERS (AIRTEL)
      {
        dataId: 531,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 900,
        size: "5.0 GB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 532,
        network: "AIRTEL",
        planType: "SME",
        amount: 900,
        size: "5.0 GB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 533,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 2500,
        size: "9.0 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 534,
        network: "AIRTEL",
        planType: "SME",
        amount: 2500,
        size: "9.0 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 535,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 19500,
        size: "100.0 GB",
        validity: "30 days",
      },
      {
        dataId: 536,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 310,
        size: "1.0 GB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 537,
        network: "AIRTEL",
        planType: "SME",
        amount: 310,
        size: "1.0 GB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 552,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 810,
        size: "4.0 GB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 553,
        network: "AIRTEL",
        planType: "SME",
        amount: 810,
        size: "4.0 GB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 554,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 350,
        size: "1.0 GB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 555,
        network: "AIRTEL",
        planType: "SME",
        amount: 350,
        size: "1.0 GB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 556,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 65,
        size: "150.0 MB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 557,
        network: "AIRTEL",
        planType: "SME",
        amount: 65,
        size: "150.0 MB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 558,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 215,
        size: "600.0 MB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 559,
        network: "AIRTEL",
        planType: "SME",
        amount: 215,
        size: "600.0 MB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 560,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 110,
        size: "300.0 MB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 561,
        network: "AIRTEL",
        planType: "SME",
        amount: 110,
        size: "300.0 MB",
        validity: "2DAYS VALIDITY",
      },

      // GLO
      {
        dataId: 285,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 400,
        size: "1.0 GB",
        validity: "30 days (C.G)",
      },
      {
        dataId: 286,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 800,
        size: "2.0 GB",
        validity: "30 days (C.G)",
      },
      {
        dataId: 287,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 1200,
        size: "3.0 GB",
        validity: "30 days (C.G)",
      },
      {
        dataId: 288,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 2000,
        size: "5.0 GB",
        validity: "30 days (C.G)",
      },
      {
        dataId: 289,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 4000,
        size: "10.0 GB",
        validity: "30 days (C.G)",
      },
      {
        dataId: 290,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 200,
        size: "500.0 MB",
        validity: "30 days (C.G)",
      },
      {
        dataId: 291,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 80,
        size: "200.0 MB",
        validity: "30 days (C.G)",
      },
      {
        dataId: 351,
        network: "GLO",
        planType: "GIFTING",
        amount: 295,
        size: "1.5 GB",
        validity: "AWOOF 1DAYS VALIDITY",
      },
      {
        dataId: 352,
        network: "GLO",
        planType: "GIFTING",
        amount: 485,
        size: "2.5 GB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 354,
        network: "GLO",
        planType: "GIFTING",
        amount: 1950,
        size: "10.0 GB",
        validity: "AWOOF 7DAYS VALIDITY",
      },
      {
        dataId: 369,
        network: "GLO",
        planType: "SME",
        amount: 295,
        size: "1.5 GB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 370,
        network: "GLO",
        planType: "SME",
        amount: 485,
        size: "2.5 GB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 371,
        network: "GLO",
        planType: "SME",
        amount: 1950,
        size: "10.0 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 546,
        network: "GLO",
        planType: "GIFTING",
        amount: 1000,
        size: "3.5 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 547,
        network: "GLO",
        planType: "SME",
        amount: 1000,
        size: "3.5 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 548,
        network: "GLO",
        planType: "GIFTING",
        amount: 2000,
        size: "8.5 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 549,
        network: "GLO",
        planType: "SME",
        amount: 2000,
        size: "8.5 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 550,
        network: "GLO",
        planType: "GIFTING",
        amount: 4850,
        size: "20.5 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 551,
        network: "GLO",
        planType: "SME",
        amount: 4850,
        size: "20.5 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 563,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 325,
        size: "1.0 GB",
        validity: "7days",
      },
      {
        dataId: 564,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 275,
        size: "1.0 GB",
        validity: "3days",
      },

      // MTN
      {
        dataId: 7,
        network: "MTN",
        planType: "SME",
        amount: 780,
        size: "1.0 GB",
        validity: "7days",
      },
      {
        dataId: 8,
        network: "MTN",
        planType: "SME",
        amount: 1450,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 44,
        network: "MTN",
        planType: "SME",
        amount: 2450,
        size: "3.5 GB",
        validity: "30 days",
      },
      {
        dataId: 219,
        network: "MTN",
        planType: "SME",
        amount: 485,
        size: "500.0 MB",
        validity: "7 days",
      },
      {
        dataId: 308,
        network: "MTN",
        planType: "SME2",
        amount: 3450,
        size: "7.0 GB",
        validity: "1month(SME)2",
      },
      {
        dataId: 310,
        network: "MTN",
        planType: "SME2",
        amount: 2450,
        size: "3.5 GB",
        validity: "1month(SME)2",
      },
      {
        dataId: 314,
        network: "MTN",
        planType: "SME2",
        amount: 1450,
        size: "2.0 GB",
        validity: "1month(SME)2",
      },
      {
        dataId: 315,
        network: "MTN",
        planType: "SME2",
        amount: 4400,
        size: "10.0 GB",
        validity: "1month(SME)2",
      },
      {
        dataId: 319,
        network: "MTN",
        planType: "SME2",
        amount: 780,
        size: "1.0 GB",
        validity: "Weekly +5MIN (SME)2",
      },
      {
        dataId: 330,
        network: "MTN",
        planType: "DATA SHARE",
        amount: 2300,
        size: "5.0 GB",
        validity: "25DAYS VALIDITY",
      },
      {
        dataId: 343,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 970,
        size: "3.2 GB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 378,
        network: "MTN",
        planType: "GIFTING",
        amount: 970,
        size: "3.2 GB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 379,
        network: "MTN",
        planType: "GIFTING",
        amount: 3450,
        size: "11.0 GB",
        validity: "7DAYS VALIDITY",
      },
      // ...continue for the rest of the MTN plans as needed

      // MTN
      {
        dataId: 403,
        network: "MTN",
        planType: "GIFTING",
        amount: 485,
        size: "1.0 GB",
        validity: "1DAY VALIDITY+5min",
      },
      {
        dataId: 404,
        network: "MTN",
        planType: "GIFTING",
        amount: 2450,
        size: "6.0 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 405,
        network: "MTN",
        planType: "GIFTING",
        amount: 17500,
        size: "75.0 GB",
        validity: "30days",
      },
      {
        dataId: 406,
        network: "MTN",
        planType: "GIFTING",
        amount: 49500,
        size: "200.0 GB",
        validity: "60days",
      },
      {
        dataId: 407,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 4450,
        size: "10.0 GB",
        validity: "+15min Monthly",
      },
      {
        dataId: 408,
        network: "MTN",
        planType: "GIFTING",
        amount: 80,
        size: "75.0 MB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 409,
        network: "MTN",
        planType: "GIFTING",
        amount: 750,
        size: "2.5 GB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 410,
        network: "MTN",
        planType: "GIFTING",
        amount: 750,
        size: "2.0 GB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 412,
        network: "MTN",
        planType: "GIFTING",
        amount: 590,
        size: "1.5 GB",
        validity: "2DAY VALIDITY",
      },
      {
        dataId: 413,
        network: "MTN",
        planType: "GIFTING",
        amount: 5000,
        size: "11.0 GB",
        validity: "25min + 30days",
      },
      {
        dataId: 414,
        network: "MTN",
        planType: "GIFTING",
        amount: 6480,
        size: "16.5 GB",
        validity: "30DAYS VALIDITY +25MIN",
      },
      {
        dataId: 416,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 7300,
        size: "20.0 GB",
        validity: "30DAYS VALIDITY",
      },
      {
        dataId: 417,
        network: "MTN",
        planType: "GIFTING",
        amount: 8950,
        size: "25.0 GB",
        validity: "30days",
      },
      {
        dataId: 419,
        network: "MTN",
        planType: "GIFTING",
        amount: 2910,
        size: "4.2 GB",
        validity: "+5mins monthly",
      },
      {
        dataId: 420,
        network: "MTN",
        planType: "GIFTING",
        amount: 4450,
        size: "10.0 GB",
        validity: "30DAYS VALIDITY +15MIN",
      },
      {
        dataId: 429,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 485,
        size: "1.0 GB",
        validity: "1DAY VALIDITY+5min",
      },
      {
        dataId: 430,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 590,
        size: "1.5 GB",
        validity: "2DAY VALIDITY",
      },
      {
        dataId: 431,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 750,
        size: "2.0 GB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 432,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 900,
        size: "2.5 GB",
        validity: "2DAYS VALIDITY",
      },
      {
        dataId: 433,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 750,
        size: "2.5 GB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 434,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 2450,
        size: "6.0 GB",
        validity: "7days validity",
      },
      {
        dataId: 438,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 2950,
        size: "4.2 GB",
        validity: "+5mins monthly",
      },
      {
        dataId: 440,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 3450,
        size: "11.0 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 441,
        network: "MTN",
        planType: "GIFTING",
        amount: 785,
        size: "1.0 GB",
        validity: "7DAYS VALIDITY +25MIN",
      },
      {
        dataId: 442,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 785,
        size: "1.0 GB",
        validity: "7DAYS VALIDITY +25MIN",
      },
      {
        dataId: 443,
        network: "MTN",
        planType: "GIFTING",
        amount: 96,
        size: "110.0 MB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 444,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 96,
        size: "110.0 MB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 445,
        network: "MTN",
        planType: "GIFTING",
        amount: 195,
        size: "230.0 MB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 446,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 195,
        size: "230.0 MB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 451,
        network: "MTN",
        planType: "GIFTING",
        amount: 1450,
        size: "2.0 GB",
        validity: "30DAYS VALIDITY",
      },
      {
        dataId: 452,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 1450,
        size: "2.0 GB",
        validity: "30DAYS VALIDITY",
      },
      {
        dataId: 453,
        network: "MTN",
        planType: "GIFTING",
        amount: 2450,
        size: "3.5 GB",
        validity: "30DAYS VALIDITY",
      },
      {
        dataId: 454,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 2450,
        size: "3.5 GB",
        validity: "30DAYS VALIDITY",
      },
      {
        dataId: 455,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 6480,
        size: "16.5 GB",
        validity: "30DAYS VALIDITY +10MIN",
      },
      {
        dataId: 456,
        network: "MTN",
        planType: "GIFTING",
        amount: 3450,
        size: "7.0 GB",
        validity: "30DAYS VALIDITY +2gbnight",
      },
      {
        dataId: 457,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 3450,
        size: "7.0 GB",
        validity: "30DAYS VALIDITY +2gbnight",
      },
      {
        dataId: 458,
        network: "MTN",
        planType: "GIFTING",
        amount: 7300,
        size: "20.0 GB",
        validity: "30DAYS VALIDITY",
      },
      {
        dataId: 459,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 8950,
        size: "25.0 GB",
        validity: "30DAYS VALIDITY",
      },
      {
        dataId: 462,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 80,
        size: "75.0 MB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 463,
        network: "MTN",
        planType: "SME2",
        amount: 5350,
        size: "12.5 GB",
        validity: "1Month",
      },
      {
        dataId: 464,
        network: "MTN",
        planType: "SME2",
        amount: 6300,
        size: "16.5 GB",
        validity: "1month",
      },
      {
        dataId: 465,
        network: "MTN",
        planType: "SME2",
        amount: 1480,
        size: "3.5 GB",
        validity: "Weekly(SME)2",
      },
      {
        dataId: 466,
        network: "MTN",
        planType: "SME2",
        amount: 2910,
        size: "4.2 GB",
        validity: "1month(SME)2",
      },
      {
        dataId: 467,
        network: "MTN",
        planType: "SME",
        amount: 965,
        size: "1.5 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 473,
        network: "MTN",
        planType: "SME2",
        amount: 10800,
        size: "36.0 GB",
        validity: "30days",
      },
      {
        dataId: 474,
        network: "MTN",
        planType: "SME2",
        amount: 15500,
        size: "65.0 GB",
        validity: "30 days",
      },
      {
        dataId: 475,
        network: "MTN",
        planType: "SME2",
        amount: 17450,
        size: "75.0 GB",
        validity: "30 days",
      },
      {
        dataId: 476,
        network: "MTN",
        planType: "SME2",
        amount: 35880,
        size: "165.0 GB",
        validity: "30 days",
      },
      {
        dataId: 479,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 1300,
        size: "2.0 GB",
        validity: "30days (C.G)",
      },
      {
        dataId: 480,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 1950,
        size: "3.0 GB",
        validity: "MONTHLY (C.G)",
      },
      {
        dataId: 481,
        network: "MTN",
        planType: "SME2",
        amount: 1300,
        size: "2000.0 MB",
        validity: "2GB MONTHLY VALIDITY",
      },
      {
        dataId: 482,
        network: "MTN",
        planType: "SME2",
        amount: 1950,
        size: "3000.0 MB",
        validity: "3GB 30days VALIDITY",
      },
      {
        dataId: 497,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 400,
        size: "500.0 MB",
        validity: "(500MB) 7 days (C.G)",
      },
      {
        dataId: 498,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 680,
        size: "1.0 GB",
        validity: "MONTHLY (C.G)",
      },
      {
        dataId: 500,
        network: "MTN",
        planType: "SME",
        amount: 400,
        size: "0.5 GB",
        validity: "(500MB) 7DAYS VALIDITY",
      },
      {
        dataId: 501,
        network: "MTN",
        planType: "SME",
        amount: 680,
        size: "1000.0 MB",
        validity: "=1GB 30days VALIDITY",
      },
      {
        dataId: 502,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 2300,
        size: "5.0 GB",
        validity: "MONTHLY VALIDITY",
      },
      {
        dataId: 503,
        network: "MTN",
        planType: "SME2",
        amount: 2300,
        size: "5000.0 MB",
        validity: "30DAYS VALIDITY",
      },
      {
        dataId: 504,
        network: "MTN",
        planType: "SME2",
        amount: 53500,
        size: "250.0 GB",
        validity: "30 days",
      },
      {
        dataId: 505,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 53500,
        size: "250.0 GB",
        validity: "30 days",
      },
      {
        dataId: 506,
        network: "MTN",
        planType: "SME2",
        amount: 24500,
        size: "90.0 GB",
        validity: "60days(2month)",
      },
      {
        dataId: 507,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 24500,
        size: "90.0 GB",
        validity: "60days(2month)",
      },
      {
        dataId: 509,
        network: "MTN",
        planType: "SME2",
        amount: 740,
        size: "2.5 GB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 510,
        network: "MTN",
        planType: "GIFTING",
        amount: 740,
        size: "2.5 GB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 511,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 740,
        size: "2.5 GB",
        validity: "1DAY VALIDITY",
      },
      {
        dataId: 512,
        network: "MTN",
        planType: "SME2",
        amount: 4900,
        size: "20.0 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 513,
        network: "MTN",
        planType: "GIFTING",
        amount: 4900,
        size: "20.0 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 514,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 4900,
        size: "20.0 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 538,
        network: "MTN",
        planType: "SME",
        amount: 2300,
        size: "5000.0 MB",
        validity: "(5GB) monthly",
      },
      {
        dataId: 539,
        network: "MTN",
        planType: "SME",
        amount: 7300,
        size: "20.0 GB",
        validity: "30 days",
      },
      {
        dataId: 562,
        network: "MTN",
        planType: "SME2",
        amount: 680,
        size: "1000.0 MB",
        validity: "30days VALIDITY(1GB)",
      },
      {
        dataId: 566,
        network: "MTN",
        planType: "DATA SHARE",
        amount: 400,
        size: "0.5 GB",
        validity: "7DAYS VALIDITY",
      },
      {
        dataId: 567,
        network: "MTN",
        planType: "DATA SHARE",
        amount: 680,
        size: "1000.0 MB",
        validity: "=(1gb) 30Days VALIDITY",
      },
      {
        dataId: 568,
        network: "MTN",
        planType: "DATA SHARE",
        amount: 1300,
        size: "2.0 GB",
        validity: "25DAYS VALIDITY",
      },
      {
        dataId: 569,
        network: "MTN",
        planType: "DATA SHARE",
        amount: 1950,
        size: "3.0 GB",
        validity: "25DAYS VALIDITY",
      },
      {
        dataId: 570,
        network: "MTN",
        planType: "GIFTING",
        amount: 2300,
        size: "5.0 GB",
        validity: "25DAYS VALIDITY",
      },
      {
        dataId: 571,
        network: "MTN",
        planType: "GIFTING",
        amount: 1900,
        size: "3.0 GB",
        validity: "25DAYS VALIDITY",
      },
      {
        dataId: 572,
        network: "MTN",
        planType: "SME",
        amount: 1950,
        size: "3000.0 GB",
        validity: "(3gb)Monthly",
      },
      {
        dataId: 573,
        network: "MTN",
        planType: "SME",
        amount: 1300,
        size: "2000.0 MB",
        validity: "=(2GB) MONTHLY VALIDITY",
      },
      {
        dataId: 574,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 680,
        size: "1000.0 MB",
        validity: "(1GB)30DAYS VALIDITY",
      },
      {
        dataId: 575,
        network: "MTN",
        planType: "GIFTING",
        amount: 680,
        size: "1000.0 MB",
        validity: "(1GB) 30DAYS",
      },
    ].map((plan) => ({ ...plan, providerId: alrahuzdata.id })),
  });

  // Add data plans for dataplus
  await prisma.dataPlan.createMany({
    data: [
      {
        dataId: 227,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 290,
        size: "1.0 GB",
        validity: "30-days",
      },
      {
        dataId: 278,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 590,
        size: "2.0 GB",
        validity: "30-days",
      },
      {
        dataId: 279,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 1475,
        size: "5.0 GB",
        validity: "30-days",
      },
      {
        dataId: 280,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 2950,
        size: "10.0 GB",
        validity: "30-days",
      },
      {
        dataId: 282,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 885,
        size: "3.0 GB",
        validity: "30-days",
      },
      {
        dataId: 283,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 4425,
        size: "15.0 GB",
        validity: "30-days",
      },
      {
        dataId: 291,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 5900,
        size: "20.0 GB",
        validity: "30-days",
      },
      {
        dataId: 292,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 150,
        size: "500.0 MB",
        validity: "30-days",
      },
      {
        dataId: 320,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 442.5,
        size: "1.5 GB",
        validity: "30-days",
      },
      {
        dataId: 321,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 95,
        size: "300.0 MB",
        validity: "30-days",
      },
      {
        dataId: 322,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 60,
        size: "100.0 MB",
        validity: "30-days",
      },
      {
        dataId: 333,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 65,
        size: "150.0 MB",
        validity: "1-day (SME)",
      },
      {
        dataId: 352,
        network: "AIRTEL",
        planType: "AWOOF DATA",
        amount: 3020,
        size: "10.0 GB",
        validity: "30-days",
      },
      {
        dataId: 372,
        network: "AIRTEL",
        planType: "AWOOF DATA",
        amount: 60,
        size: "150.0 MB",
        validity: "1-day (SME)",
      },
      {
        dataId: 375,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 3020,
        size: "10.0 GB",
        validity: "30-days (SME)",
      },
      {
        dataId: 384,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 2020,
        size: "7.0 GB",
        validity: "7-days (SME)",
      },
      {
        dataId: 385,
        network: "AIRTEL",
        planType: "AWOOF DATA",
        amount: 2020,
        size: "7.0 GB",
        validity: "7-days",
      },
      {
        dataId: 393,
        network: "AIRTEL",
        planType: "SME2",
        amount: 1035,
        size: "3.0 GB",
        validity: "7-days (SME)",
      },
      {
        dataId: 397,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 320.5,
        size: "1.0 GB",
        validity: "3-days (social)",
      },
      {
        dataId: 398,
        network: "AIRTEL",
        planType: "AWOOF DATA",
        amount: 320,
        size: "1.0 GB",
        validity: "3-days (Social)",
      },
      {
        dataId: 401,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 490,
        size: "500.0 MB",
        validity: "7-days (Gifting)",
      },
      {
        dataId: 402,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 1480,
        size: "2.0 GB",
        validity: "30-days (Gifting)",
      },
      {
        dataId: 403,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 1950,
        size: "3.0 GB",
        validity: "30-days (Gifting)",
      },
      {
        dataId: 404,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 2450,
        size: "4.0 GB",
        validity: "30-days (Gifting)",
      },
      {
        dataId: 405,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 2950,
        size: "8.0 GB",
        validity: "30-days (Gifting)",
      },
      {
        dataId: 406,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 4880,
        size: "13.0 GB",
        validity: "30-days (Gifting)",
      },
      {
        dataId: 407,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 5895,
        size: "18.0 GB",
        validity: "30-days (Gifting)",
      },
      {
        dataId: 408,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 7850,
        size: "25.0 GB",
        validity: "30-days (Gifting)",
      },
      {
        dataId: 409,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 9800,
        size: "35.0 GB",
        validity: "30-days (Gifting)",
      },
      {
        dataId: 410,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 2975,
        size: "10.0 GB",
        validity: "7-days (Gifting)",
      },
      {
        dataId: 416,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 985,
        size: "1.5 GB",
        validity: "7-days (Gifting)",
      },
      {
        dataId: 425,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 785,
        size: "1.0 GB",
        validity: "7-days (Gifting)",
      },
      {
        dataId: 426,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 1480,
        size: "3.5 GB",
        validity: "7-days (Gifting)",
      },
      {
        dataId: 427,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 2460,
        size: "6.0 GB",
        validity: "7-days (Gifting)",
      },
      {
        dataId: 435,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 220,
        size: "600.0 MB",
        validity: "2-days",
      },
      {
        dataId: 436,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 115,
        size: "300.0 MB",
        validity: "2-days",
      },
      {
        dataId: 437,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 520,
        size: "2.0 GB",
        validity: "2-days",
      },
      {
        dataId: 438,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 350,
        size: "1.0 GB",
        validity: "1-day",
      },
      {
        dataId: 440,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 420,
        size: "1.5 GB",
        validity: "1-day",
      },
      {
        dataId: 441,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 520,
        size: "1.0 GB",
        validity: "1-day (1GB+1GB)",
      },
      {
        dataId: 442,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 520,
        size: "1.5 GB",
        validity: "7-days (Social plan)",
      },
      {
        dataId: 443,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 765,
        size: "4.0 GB",
        validity: "2-days(Awoof)",
      },
      {
        dataId: 444,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 1490,
        size: "3.5 GB",
        validity: "7-days (3.5GB+3.5GB Awoof)",
      },
      {
        dataId: 452,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 980,
        size: "3.0 GB",
        validity: "2-days",
      },
      {
        dataId: 453,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 1475,
        size: "5.0 GB",
        validity: "2-days",
      },
      {
        dataId: 232,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 210,
        size: "500.0 MB",
        validity: "30-days",
      },
      {
        dataId: 233,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 400,
        size: "1.024 GB",
        validity: "30-days",
      },
      {
        dataId: 284,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 1200,
        size: "3.072 GB",
        validity: "30-days",
      },
      {
        dataId: 285,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 4000,
        size: "10.24 GB",
        validity: "30-days",
      },
      {
        dataId: 287,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 2000,
        size: "5.12 GB",
        validity: "30-days",
      },
      {
        dataId: 288,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 95,
        size: "200.0 MB",
        validity: "30-days",
      },
      {
        dataId: 289,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 800,
        size: "2.048 GB",
        validity: "30-days",
      },
      {
        dataId: 340,
        network: "GLO",
        planType: "AWOOF DATA",
        amount: 189,
        size: "750.0 MB",
        validity: "1-day",
      },
      {
        dataId: 342,
        network: "GLO",
        planType: "AWOOF DATA",
        amount: 288,
        size: "1.5 GB",
        validity: "1-day",
      },
      {
        dataId: 343,
        network: "GLO",
        planType: "AWOOF DATA",
        amount: 475,
        size: "2.5 GB",
        validity: "2-days",
      },
      {
        dataId: 344,
        network: "GLO",
        planType: "AWOOF DATA",
        amount: 1895,
        size: "10.0 GB",
        validity: "7-days",
      },
      {
        dataId: 360,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 195,
        size: "750.0 MB",
        validity: "1-day (SME)",
      },
      {
        dataId: 361,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 288,
        size: "1.5 GB",
        validity: "1-day (SME)",
      },
      {
        dataId: 363,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 1895,
        size: "10.0 GB",
        validity: "7-days (SME)",
      },
      {
        dataId: 364,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 475,
        size: "2.5 GB",
        validity: "2-days (SME)",
      },
      {
        dataId: 446,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 270,
        size: "1.024 GB",
        validity: "3-days",
      },
      {
        dataId: 447,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 320,
        size: "1.024 GB",
        validity: "7-days",
      },
      {
        dataId: 448,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 805,
        size: "3.072 GB",
        validity: "3-days",
      },
      {
        dataId: 449,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 945,
        size: "3.072 GB",
        validity: "7-days",
      },
      {
        dataId: 450,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 1345,
        size: "5.0 GB",
        validity: "3-days",
      },
      {
        dataId: 451,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 1575,
        size: "5.0 GB",
        validity: "7-days",
      },
      {
        dataId: 207,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 780,
        size: "1.0 GB",
        validity: "7-days",
      },
      {
        dataId: 208,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 1460,
        size: "2.0 GB",
        validity: "30-days",
      },
      {
        dataId: 209,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 1490,
        size: "1.8 GB",
        validity: "30-days",
      },
      {
        dataId: 212,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 490,
        size: "500.0 MB",
        validity: "7-days",
      },
      {
        dataId: 304,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 2429,
        size: "3.5 GB",
        validity: "30-days",
      },
      {
        dataId: 336,
        network: "MTN",
        planType: "AWOOF DATA",
        amount: 995,
        size: "3.2 GB",
        validity: "2-days",
      },
      {
        dataId: 337,
        network: "MTN",
        planType: "AWOOF DATA",
        amount: 3395,
        size: "11.0 GB",
        validity: "7-days",
      },
      {
        dataId: 338,
        network: "MTN",
        planType: "AWOOF DATA",
        amount: 490,
        size: "1.0 GB",
        validity: "1-day",
      },
      {
        dataId: 346,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 995,
        size: "3.2 GB",
        validity: "2-days",
      },
      {
        dataId: 347,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 3395,
        size: "11.0 GB",
        validity: "7-days",
      },
      {
        dataId: 359,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 490,
        size: "1.0 GB",
        validity: "1-day",
      },
      {
        dataId: 386,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 6300,
        size: "16.5 GB",
        validity: "30-days",
      },
      {
        dataId: 390,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 3385,
        size: "7.0 GB",
        validity: "30-days",
      },
      {
        dataId: 391,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 2425,
        size: "6.0 GB",
        validity: "7-days",
      },
      {
        dataId: 392,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 5345,
        size: "12.5 GB",
        validity: "30-days",
      },
      {
        dataId: 411,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 74,
        size: "75.0 MB",
        validity: "1-day",
      },
      {
        dataId: 412,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 98,
        size: "110.0 MB",
        validity: "1-day",
      },
      {
        dataId: 413,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 198,
        size: "230.0 MB",
        validity: "1-day",
      },
      {
        dataId: 414,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 440,
        size: "750.0 MB",
        validity: "3-days (+1hr Youtube IT Tiktk)",
      },
      {
        dataId: 415,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 1950,
        size: "2.7 GB",
        validity: "30-days",
      },
      {
        dataId: 417,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 737,
        size: "2.0 GB",
        validity: "2-days",
      },
      {
        dataId: 418,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 885,
        size: "2.5 GB",
        validity: "2-days",
      },
      {
        dataId: 419,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 445,
        size: "1.2 GB",
        validity: "30-days (All social only)",
      },
      {
        dataId: 420,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 348,
        size: "500.0 MB",
        validity: "1-day",
      },
      {
        dataId: 432,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 4900,
        size: "20.0 GB",
        validity: "7-days",
      },
      {
        dataId: 433,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 4380,
        size: "10.0 GB",
        validity: "30-days",
      },
      {
        dataId: 445,
        network: "MTN",
        planType: "SME",
        amount: 420,
        size: "500.0 MB",
        validity: "7-days (DS)",
      },
      {
        dataId: 454,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 7300,
        size: "20.0 GB",
        validity: "30-days",
      },
      {
        dataId: 455,
        network: "MTN",
        planType: "SME",
        amount: 650,
        size: "1.0 GB",
        validity: "30-days (DS)",
      },
      {
        dataId: 456,
        network: "MTN",
        planType: "SME",
        amount: 1280,
        size: "2.0 GB",
        validity: "30-days (DS)",
      },
      {
        dataId: 457,
        network: "MTN",
        planType: "SME",
        amount: 1895,
        size: "3.0 GB",
        validity: "30-days (DS)",
      },
      {
        dataId: 458,
        network: "MTN",
        planType: "SME",
        amount: 2300,
        size: "5.0 GB",
        validity: "30-days (DS)",
      },
    ].map((plan) => ({ ...plan, providerId: dataplus.id })),
  });

  await prisma.dataPlan.createMany({
    data: [
      {
        dataId: 105,
        network: "MTN",
        planType: "CORPORATE-GIFTING",
        amount: 500,
        size: "500MB",
        validity: "7 days",
      },
      {
        dataId: 106,
        network: "MTN",
        planType: "CORPORATE-GIFTING",
        amount: 800,
        size: "1GB",
        validity: "7 days",
      },
      {
        dataId: 108,
        network: "MTN",
        planType: "CORPORATE-GIFTING",
        amount: 560,
        size: "2GB",
        validity: "30 days",
      },
      {
        dataId: 189,
        network: "MTN",
        planType: "CORPORATE-GIFTING",
        amount: 1500,
        size: "3GB",
        validity: "7 days",
      },
      {
        dataId: 191,
        network: "MTN",
        planType: "CORPORATE-GIFTING",
        amount: 3500,
        size: "11GB",
        validity: "30 days",
      },
      {
        dataId: 202,
        network: "MTN",
        planType: "CORPORATE-GIFTING",
        amount: 11000,
        size: "36GB",
        validity: "30 days",
      },
      {
        dataId: 2213,
        network: "MTN",
        planType: "DIRECT-COUPON",
        amount: 252,
        size: "1GB",
        validity: "7 days",
      },
      {
        dataId: 2253,
        network: "MTN",
        planType: "DIRECT-COUPON",
        amount: 510,
        size: "2GB",
        validity: "30 days",
      },
      {
        dataId: 2304,
        network: "MTN",
        planType: "GIFTING",
        amount: 1500,
        size: "2GB",
        validity: "30 days",
      },
      {
        dataId: 2305,
        network: "MTN",
        planType: "GIFTING",
        amount: 2500,
        size: "3.5GB",
        validity: "30 days",
      },
      {
        dataId: 2306,
        network: "MTN",
        planType: "GIFTING",
        amount: 3500,
        size: "7GB",
        validity: "30 days",
      },
      {
        dataId: 2307,
        network: "MTN",
        planType: "GIFTING",
        amount: 4500,
        size: "10GB",
        validity: "30 days",
      },
      {
        dataId: 2308,
        network: "MTN",
        planType: "GIFTING",
        amount: 5000,
        size: "14.5GB",
        validity: "30 days",
      },
      {
        dataId: 2309,
        network: "MTN",
        planType: "GIFTING",
        amount: 6500,
        size: "16.5GB",
        validity: "30 days",
      },
      {
        dataId: 2310,
        network: "MTN",
        planType: "GIFTING",
        amount: 7500,
        size: "20GB",
        validity: "30 days",
      },
      {
        dataId: 2298,
        network: "MTN",
        planType: "GIFTING",
        amount: 350,
        size: "500MB",
        validity: "1 day",
      },
      {
        dataId: 2299,
        network: "MTN",
        planType: "GIFTING",
        amount: 500,
        size: "1GB",
        validity: "1 day",
      },
      {
        dataId: 2300,
        network: "MTN",
        planType: "GIFTING",
        amount: 600,
        size: "1.5GB",
        validity: "2 days",
      },
      {
        dataId: 2301,
        network: "MTN",
        planType: "GIFTING",
        amount: 750,
        size: "2GB",
        validity: "2 days",
      },
      {
        dataId: 2302,
        network: "MTN",
        planType: "GIFTING",
        amount: 900,
        size: "2.5GB",
        validity: "2 days",
      },
      {
        dataId: 2303,
        network: "MTN",
        planType: "GIFTING",
        amount: 1000,
        size: "3.2GB",
        validity: "2 days",
      },
      {
        dataId: 1,
        network: "MTN",
        planType: "SME",
        amount: 650,
        size: "1GB",
        validity: "Monthly plan",
      },
      {
        dataId: 2,
        network: "MTN",
        planType: "SME",
        amount: 1400,
        size: "2GB",
        validity: "30 days",
      },
      {
        dataId: 3,
        network: "MTN",
        planType: "SME",
        amount: 2500,
        size: "5GB",
        validity: "30 days",
      },
      {
        dataId: 20,
        network: "MTN",
        planType: "SME",
        amount: 500,
        size: "500MB",
        validity: "30 days",
      },
      {
        dataId: 90,
        network: "MTN",
        planType: "SME",
        amount: 1800,
        size: "3GB",
        validity: "30 days",
      },
      {
        dataId: 91,
        network: "MTN",
        planType: "SME",
        amount: 5000,
        size: "10GB",
        validity: "30 days",
      },
      {
        dataId: 2255,
        network: "MTN",
        planType: "SME2",
        amount: 136,
        size: "500MB",
        validity: "30 days",
      },
      {
        dataId: 2256,
        network: "MTN",
        planType: "SME2",
        amount: 274,
        size: "1GB",
        validity: "30 days",
      },
      {
        dataId: 2257,
        network: "MTN",
        planType: "SME2",
        amount: 542,
        size: "2GB",
        validity: "30 days",
      },
      {
        dataId: 2258,
        network: "MTN",
        planType: "SME2",
        amount: 813,
        size: "3GB",
        validity: "30 days",
      },
      {
        dataId: 2259,
        network: "MTN",
        planType: "SME2",
        amount: 1355,
        size: "5GB",
        validity: "30 days",
      },
      {
        dataId: 2260,
        network: "MTN",
        planType: "SME2",
        amount: 2694,
        size: "10GB",
        validity: "30 days",
      },
      {
        dataId: 12,
        network: "AIRTEL",
        planType: "CORPORATE-GIFTING",
        amount: 500,
        size: "500MB",
        validity: "7 days",
      },
      {
        dataId: 13,
        network: "AIRTEL",
        planType: "CORPORATE-GIFTING",
        amount: 850,
        size: "1GB",
        validity: "7 days",
      },
      {
        dataId: 17,
        network: "AIRTEL",
        planType: "CORPORATE-GIFTING",
        amount: 1550,
        size: "2GB",
        validity: "30 days",
      },
      {
        dataId: 19,
        network: "AIRTEL",
        planType: "CORPORATE-GIFTING",
        amount: 2000,
        size: "3GB",
        validity: "30 days",
      },
      {
        dataId: 21,
        network: "AIRTEL",
        planType: "CORPORATE-GIFTING",
        amount: 2500,
        size: "4GB",
        validity: "30 days",
      },
      {
        dataId: 2263,
        network: "AIRTEL",
        planType: "CORPORATE-GIFTING",
        amount: 70,
        size: "150MB",
        validity: "1 day",
      },
      {
        dataId: 2264,
        network: "AIRTEL",
        planType: "CORPORATE-GIFTING",
        amount: 150,
        size: "300MB",
        validity: "2 days",
      },
      {
        dataId: 2265,
        network: "AIRTEL",
        planType: "CORPORATE-GIFTING",
        amount: 3100,
        size: "8GB",
        validity: "30 Days",
      },
      {
        dataId: 2266,
        network: "AIRTEL",
        planType: "CORPORATE-GIFTING",
        amount: 5000,
        size: "13GB",
        validity: "30 Days",
      },
      {
        dataId: 2236,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 792,
        size: "3GB",
        validity: "30 days",
      },
      {
        dataId: 2237,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 2024,
        size: "4.5GB",
        validity: "30 days",
      },
      {
        dataId: 2238,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 2300,
        size: "6GB",
        validity: "30 days",
      },
      {
        dataId: 2239,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 3036,
        size: "10GB",
        validity: "30 days",
      },
      {
        dataId: 2240,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 4000,
        size: "15GB",
        validity: "30 days",
      },
      {
        dataId: 2241,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 5000,
        size: "18GB",
        validity: "30 days",
      },
      {
        dataId: 2242,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 8000,
        size: "30GB",
        validity: "30 days",
      },
      {
        dataId: 2243,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 10120,
        size: "40GB",
        validity: "30 days",
      },
      {
        dataId: 2244,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 15180,
        size: "75GB",
        validity: "30 days",
      },
      {
        dataId: 2245,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 20240,
        size: "120GB",
        validity: "30 days",
      },
      {
        dataId: 2246,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 500,
        size: "750MB",
        validity: "7 days",
      },
      {
        dataId: 2247,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 1000,
        size: "1.2GB",
        validity: "30 days",
      },
      {
        dataId: 2248,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 1012,
        size: "1.5GB",
        validity: "30 days",
      },
      {
        dataId: 2249,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 350,
        size: "350MB",
        validity: "7 days",
      },
      {
        dataId: 2250,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 200,
        size: "200MB",
        validity: "1 day",
      },
      {
        dataId: 2252,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 100,
        size: "100MB",
        validity: "1 day",
      },
      {
        dataId: 2254,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 500,
        size: "1GB",
        validity: "7 days",
      },
      {
        dataId: 2267,
        network: "AIRTEL",
        planType: "SME",
        amount: 130,
        size: "500MB",
        validity: "7 days",
      },
      {
        dataId: 2268,
        network: "AIRTEL",
        planType: "SME",
        amount: 90,
        size: "250MB",
        validity: "14 days",
      },
      {
        dataId: 2269,
        network: "AIRTEL",
        planType: "SME",
        amount: 225,
        size: "1GB",
        validity: "2 days",
      },
      {
        dataId: 2270,
        network: "AIRTEL",
        planType: "SME",
        amount: 526,
        size: "3GB",
        validity: "7 days",
      },
      {
        dataId: 2280,
        network: "AIRTEL",
        planType: "SME",
        amount: 335,
        size: "2GB",
        validity: "2 days",
      },
      {
        dataId: 2282,
        network: "AIRTEL",
        planType: "SME",
        amount: 1030,
        size: "4GB",
        validity: "30 days",
      },
      {
        dataId: 2283,
        network: "AIRTEL",
        planType: "SME",
        amount: 2070,
        size: "10GB",
        validity: "30 days",
      },
      {
        dataId: 2284,
        network: "AIRTEL",
        planType: "SME",
        amount: 3090,
        size: "15GB",
        validity: "30 days",
      },
      {
        dataId: 2289,
        network: "AIRTEL",
        planType: "SME",
        amount: 257,
        size: "1GB",
        validity: "7 days",
      },
      {
        dataId: 2290,
        network: "AIRTEL",
        planType: "SME",
        amount: 360,
        size: "1.5GB",
        validity: "7 days",
      },
      {
        dataId: 2291,
        network: "AIRTEL",
        planType: "SME",
        amount: 535,
        size: "2GB",
        validity: "14 days",
      },
      {
        dataId: 2292,
        network: "AIRTEL",
        planType: "SME",
        amount: 1240,
        size: "5GB",
        validity: "14 days",
      },
      {
        dataId: 2293,
        network: "AIRTEL",
        planType: "SME",
        amount: 3640,
        size: "20GB",
        validity: "30 days",
      },
      {
        dataId: 2294,
        network: "AIRTEL",
        planType: "SME",
        amount: 6080,
        size: "40GB",
        validity: "30 days",
      },
      {
        dataId: 5,
        network: "GLO",
        planType: "CORPORATE-GIFTING",
        amount: 135,
        size: "300MB",
        validity: "30 days",
      },
      {
        dataId: 28,
        network: "GLO",
        planType: "CORPORATE-GIFTING",
        amount: 110,
        size: "200MB",
        validity: "30 days",
      },
      {
        dataId: 137,
        network: "GLO",
        planType: "CORPORATE-GIFTING",
        amount: 440,
        size: "1GB",
        validity: "30 days",
      },
      {
        dataId: 139,
        network: "GLO",
        planType: "CORPORATE-GIFTING",
        amount: 900,
        size: "2GB",
        validity: "30 days",
      },
      {
        dataId: 140,
        network: "GLO",
        planType: "CORPORATE-GIFTING",
        amount: 1371,
        size: "5GB",
        validity: "30 days",
      },
      {
        dataId: 2204,
        network: "GLO",
        planType: "CORPORATE-GIFTING",
        amount: 230,
        size: "500MB",
        validity: "30 days",
      },
      {
        dataId: 2205,
        network: "GLO",
        planType: "CORPORATE-GIFTING",
        amount: 4500,
        size: "10GB",
        validity: "30 days",
      },
      {
        dataId: 2214,
        network: "GLO",
        planType: "CORPORATE-GIFTING",
        amount: 1300,
        size: "3GB",
        validity: "30 days",
      },
      {
        dataId: 2286,
        network: "GLO",
        planType: "SME",
        amount: 320,
        size: "2GB",
        validity: "1 day",
      },
      {
        dataId: 2287,
        network: "GLO",
        planType: "SME",
        amount: 490,
        size: "3.5GB",
        validity: "2 days",
      },
      {
        dataId: 2288,
        network: "GLO",
        planType: "SME",
        amount: 1943,
        size: "15GB",
        validity: "7 days",
      },
      {
        dataId: 2295,
        network: "GLO",
        planType: "SME",
        amount: 200,
        size: "1GB",
        validity: "1 day",
      },
      {
        dataId: 87,
        network: "9MOBILE",
        planType: "CORPORATE-GIFTING",
        amount: 155,
        size: "1GB",
        validity: "30 days",
      },
      {
        dataId: 2210,
        network: "9MOBILE",
        planType: "CORPORATE-GIFTING",
        amount: 300,
        size: "2GB",
        validity: "30 days",
      },
      {
        dataId: 2211,
        network: "9MOBILE",
        planType: "CORPORATE-GIFTING",
        amount: 450,
        size: "3GB",
        validity: "30 days",
      },
      {
        dataId: 2212,
        network: "9MOBILE",
        planType: "CORPORATE-GIFTING",
        amount: 600,
        size: "4GB",
        validity: "30 days",
      },
      {
        dataId: 2218,
        network: "9MOBILE",
        planType: "CORPORATE-GIFTING",
        amount: 670,
        size: "4.5GB",
        validity: "30 days",
      },
      {
        dataId: 2219,
        network: "9MOBILE",
        planType: "CORPORATE-GIFTING",
        amount: 750,
        size: "5GB",
        validity: "30 days",
      },
      {
        dataId: 2220,
        network: "9MOBILE",
        planType: "CORPORATE-GIFTING",
        amount: 1500,
        size: "10GB",
        validity: "30 days",
      },
      {
        dataId: 2221,
        network: "9MOBILE",
        planType: "CORPORATE-GIFTING",
        amount: 2250,
        size: "15GB",
        validity: "30 days",
      },
      {
        dataId: 2229,
        network: "9MOBILE",
        planType: "CORPORATE-GIFTING",
        amount: 75,
        size: "500MB",
        validity: "30 days",
      },
      {
        dataId: 11,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 440,
        size: "500MB",
        validity: "30 days",
      },
      {
        dataId: 82,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 400,
        size: "1GB",
        validity: "7 days",
      },
      {
        dataId: 83,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1056,
        size: "2GB",
        validity: "30 days",
      },
      {
        dataId: 84,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1000,
        size: "2.5GB",
        validity: "30 days",
      },
      {
        dataId: 85,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 2000,
        size: "5.5GB",
        validity: "30 days",
      },
      {
        dataId: 86,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 3000,
        size: "12GB",
        validity: "30 days",
      },
      {
        dataId: 2215,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 4400,
        size: "15GB",
        validity: "30 days",
      },
      {
        dataId: 2231,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1500,
        size: "7GB",
        validity: "7 days",
      },
      {
        dataId: 2232,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1500,
        size: "3.6GB",
        validity: "30 days",
      },
      {
        dataId: 2233,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 270,
        size: "1GB",
        validity: "1 day",
      },
    ].map((plan) => ({ ...plan, providerId: ameentaccetelecom.id })),
  });
}

main()
  .then(() => console.log("Data plans added successfully"))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
