import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // Create providers
  const anwardataco = await prisma.provider.upsert({
    where: { name: "anwardataco" },
    create: { name: "anwardataco" },
    update: {},
  });

  const alrahuzdata = await prisma.provider.upsert({
    where: { name: "alrahuzdata" },
    create: { name: "alrahuzdata" },
    update: {},
  });

  const dataplus = await prisma.provider.upsert({
    where: { name: "dataplus" },
    create: { name: "dataplus" },
    update: {},
  });

  // Add data plans for anwardataco
  await prisma.dataPlan.createMany({
    data: [
      // MTN SME
      {
        dataId: 225,
        network: "MTN",
        planType: "SME",
        amount: 129,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 7,
        network: "MTN",
        planType: "SME",
        amount: 259,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 8,
        network: "MTN",
        planType: "SME",
        amount: 520,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 44,
        network: "MTN",
        planType: "SME",
        amount: 777,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 11,
        network: "MTN",
        planType: "SME",
        amount: 1295,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 224,
        network: "MTN",
        planType: "SME",
        amount: 2590,
        size: "10.0 GB",
        validity: "30 days",
      },

      // MTN SME 2
      {
        dataId: 277,
        network: "MTN",
        planType: "SME 2",
        amount: 130,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 263,
        network: "MTN",
        planType: "SME 2",
        amount: 260,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 269,
        network: "MTN",
        planType: "SME 2",
        amount: 512,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 268,
        network: "MTN",
        planType: "SME 2",
        amount: 780,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 308,
        network: "MTN",
        planType: "SME 2",
        amount: 390,
        size: "1.5 GB",
        validity: "30 days",
      },
      {
        dataId: 267,
        network: "MTN",
        planType: "SME 2",
        amount: 1280,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 307,
        network: "MTN",
        planType: "SME 2",
        amount: 1040,
        size: "4.0 GB",
        validity: "30 days",
      },
      {
        dataId: 266,
        network: "MTN",
        planType: "SME 2",
        amount: 2600,
        size: "10.0 GB",
        validity: "30 days",
      },

      // MTN GIFTING
      {
        dataId: 306,
        network: "MTN",
        planType: "GIFTING",
        amount: 125,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 301,
        network: "MTN",
        planType: "GIFTING",
        amount: 250,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 302,
        network: "MTN",
        planType: "GIFTING",
        amount: 500,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 303,
        network: "MTN",
        planType: "GIFTING",
        amount: 750,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 304,
        network: "MTN",
        planType: "GIFTING",
        amount: 1300,
        size: "5.0 GB",
        validity: "30 days",
      },

      // MTN CORPORATE GIFTING
      {
        dataId: 218,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 132,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 213,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 265,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 214,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 530,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 215,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 795,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 216,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 1325,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 217,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 2650,
        size: "10.0 GB",
        validity: "30 days",
      },
      {
        dataId: 220,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 3975,
        size: "15.0 GB",
        validity: "30 days",
      },
      {
        dataId: 287,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 5200,
        size: "20.0 GB",
        validity: "30 days",
      },
      {
        dataId: 242,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 87,
        size: "250.0 MB",
        validity: "30 days",
      },
      {
        dataId: 243,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 67,
        size: "150.0 MB",
        validity: "30 days",
      },
      {
        dataId: 244,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 37,
        size: "50.0 MB",
        validity: "30 days",
      },

      // MTN DATA COUPONS
      {
        dataId: 299,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 248,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 296,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 493,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 309,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 738,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 310,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 1228,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 311,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 125,
        size: "500.0 MB",
        validity: "30 days",
      },

      // AIRTEL CORPORATE GIFTING
      {
        dataId: 226,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 50,
        size: "100.0 MB",
        validity: "7 days",
      },
      {
        dataId: 228,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 140,
        size: "500.0 MB",
        validity: "14 days",
      },
      {
        dataId: 229,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 280,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 230,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 560,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 231,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 1400,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 238,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 4200,
        size: "15.0 GB",
        validity: "30 days",
      },
      {
        dataId: 239,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 5600,
        size: "20.0 GB",
        validity: "30 days",
      },
      {
        dataId: 314,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 85,
        size: "300.0 MB",
        validity: "30 days",
      },
      {
        dataId: 313,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 2750,
        size: "10.0 GB",
        validity: "30 days",
      },

      // GLO GIFTING
      {
        dataId: 194,
        network: "GLO",
        planType: "GIFTING",
        amount: 475,
        size: "1.05 GB",
        validity: "14 days",
      },
      {
        dataId: 195,
        network: "GLO",
        planType: "GIFTING",
        amount: 960,
        size: "2.5 GB",
        validity: "30 days",
      },
      {
        dataId: 196,
        network: "GLO",
        planType: "GIFTING",
        amount: 1420,
        size: "4.1 GB",
        validity: "30 days",
      },
      {
        dataId: 198,
        network: "GLO",
        planType: "GIFTING",
        amount: 1890,
        size: "7.7 GB",
        validity: "30 days",
      },
      {
        dataId: 199,
        network: "GLO",
        planType: "GIFTING",
        amount: 2700,
        size: "10.0 GB",
        validity: "30 days",
      },
      {
        dataId: 200,
        network: "GLO",
        planType: "GIFTING",
        amount: 2820,
        size: "13.25 GB",
        validity: "30 days",
      },
      {
        dataId: 201,
        network: "GLO",
        planType: "GIFTING",
        amount: 4230,
        size: "18.25 GB",
        validity: "30 days",
      },
      {
        dataId: 202,
        network: "GLO",
        planType: "GIFTING",
        amount: 6750,
        size: "29.5 GB",
        validity: "30 days",
      },
      {
        dataId: 203,
        network: "GLO",
        planType: "GIFTING",
        amount: 8430,
        size: "50.0 GB",
        validity: "30 days",
      },
      {
        dataId: 204,
        network: "GLO",
        planType: "GIFTING",
        amount: 13050,
        size: "93.0 GB",
        validity: "30 days",
      },
      {
        dataId: 205,
        network: "GLO",
        planType: "GIFTING",
        amount: 16200,
        size: "119.0 GB",
        validity: "30 days",
      },
      {
        dataId: 206,
        network: "GLO",
        planType: "GIFTING",
        amount: 18000,
        size: "138.0 GB",
        validity: "30 days",
      },

      // GLO CORPORATE GIFTING
      {
        dataId: 246,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 1325,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 247,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 132,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 248,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 530,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 249,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 53,
        size: "200.0 MB",
        validity: "14 days",
      },
      {
        dataId: 250,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 265,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 251,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 2650,
        size: "10.0 GB",
        validity: "30 days",
      },
      {
        dataId: 252,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 795,
        size: "3.0 GB",
        validity: "30 days",
      },

      // 9MOBILE GIFTING
      {
        dataId: 183,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 890,
        size: "1.5 GB",
        validity: "30 days",
      },
      {
        dataId: 184,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1060,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 185,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1340,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 186,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1770,
        size: "4.5 GB",
        validity: "30 days",
      },
      {
        dataId: 187,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 3540,
        size: "11.0 GB",
        validity: "30 days",
      },
      {
        dataId: 188,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 2550,
        size: "15.0 GB",
        validity: "30 days",
      },
      {
        dataId: 189,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 8840,
        size: "40.0 GB",
        validity: "30 days",
      },
      {
        dataId: 190,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 12330,
        size: "75.0 GB",
        validity: "30 days",
      },

      // 9MOBILE CORPORATE GIFTING
      {
        dataId: 271,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 170,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 256,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 120,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 258,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 340,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 259,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 255,
        size: "1.5 GB",
        validity: "30 days",
      },
      {
        dataId: 260,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 510,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 261,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 850,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 262,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 1700,
        size: "10.0 GB",
        validity: "30 days",
      },
      {
        dataId: 270,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 680,
        size: "4.0 GB",
        validity: "30 days",
      },
      {
        dataId: 281,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 85,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 282,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 40,
        size: "100.0 MB",
        validity: "30 days",
      },
      {
        dataId: 283,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 30,
        size: "25.0 MB",
        validity: "30 days",
      },
      {
        dataId: 284,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 20,
        size: "15.0 MB",
        validity: "30 days",
      },
      {
        dataId: 286,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 3400,
        size: "20.0 GB",
        validity: "30 days",
      },
    ].map((plan) => ({ ...plan, providerId: anwardataco.id })),
  });

  // Add data plans for alrahuzdata
  await prisma.dataPlan.createMany({
    data: [
      // MTN SME
      {
        dataId: 219,
        network: "MTN",
        planType: "SME",
        amount: 129,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 7,
        network: "MTN",
        planType: "SME",
        amount: 258,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 8,
        network: "MTN",
        planType: "SME",
        amount: 516,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 44,
        network: "MTN",
        planType: "SME",
        amount: 774,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 11,
        network: "MTN",
        planType: "SME",
        amount: 1290,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 226,
        network: "MTN",
        planType: "SME",
        amount: 2580,
        size: "10.0 GB",
        validity: "30 days",
      },

      // MTN SME 2
      {
        dataId: 307,
        network: "MTN",
        planType: "SME 2",
        amount: 15,
        size: "50.0 MB",
        validity: "7 days",
      },
      {
        dataId: 312,
        network: "MTN",
        planType: "SME 2",
        amount: 20,
        size: "20.0 MB",
        validity: "1 month",
      },
      {
        dataId: 311,
        network: "MTN",
        planType: "SME 2",
        amount: 24,
        size: "25.0 MB",
        validity: "1 month",
      },
      {
        dataId: 313,
        network: "MTN",
        planType: "SME 2",
        amount: 65,
        size: "100.0 MB",
        validity: "1 month",
      },
      {
        dataId: 306,
        network: "MTN",
        planType: "SME 2",
        amount: 134,
        size: "500.0 MB",
        validity: "1 month",
      },
      {
        dataId: 319,
        network: "MTN",
        planType: "SME 2",
        amount: 268,
        size: "1.0 GB",
        validity: "1 month",
      },
      {
        dataId: 314,
        network: "MTN",
        planType: "SME 2",
        amount: 402,
        size: "1.5 GB",
        validity: "1 month",
      },
      {
        dataId: 318,
        network: "MTN",
        planType: "SME 2",
        amount: 536,
        size: "2.0 GB",
        validity: "1 month",
      },
      {
        dataId: 317,
        network: "MTN",
        planType: "SME 2",
        amount: 804,
        size: "3.0 GB",
        validity: "1 month",
      },
      {
        dataId: 320,
        network: "MTN",
        planType: "SME 2",
        amount: 1072,
        size: "4.0 GB",
        validity: "1 month",
      },
      {
        dataId: 316,
        network: "MTN",
        planType: "SME 2",
        amount: 1340,
        size: "5.0 GB",
        validity: "1 month",
      },
      {
        dataId: 309,
        network: "MTN",
        planType: "SME 2",
        amount: 1608,
        size: "6.0 GB",
        validity: "1 month",
      },
      {
        dataId: 308,
        network: "MTN",
        planType: "SME 2",
        amount: 1876,
        size: "7.0 GB",
        validity: "1 month",
      },
      {
        dataId: 315,
        network: "MTN",
        planType: "SME 2",
        amount: 2680,
        size: "10.0 GB",
        validity: "1 month",
      },

      // MTN GIFTING
      {
        dataId: 377,
        network: "MTN",
        planType: "GIFTING",
        amount: 220,
        size: "1.0 GB",
        validity: "1 day",
      },
      {
        dataId: 378,
        network: "MTN",
        planType: "GIFTING",
        amount: 520,
        size: "3.5 GB",
        validity: "2 days",
      },
      {
        dataId: 379,
        network: "MTN",
        planType: "GIFTING",
        amount: 2040,
        size: "15.0 GB",
        validity: "7 days",
      },

      // MTN CORPORATE GIFTING
      {
        dataId: 254,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 20,
        size: "50.0 MB",
        validity: "1 month",
      },
      {
        dataId: 255,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 55,
        size: "150.0 MB",
        validity: "1 month",
      },
      {
        dataId: 256,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 70,
        size: "250.0 MB",
        validity: "1 month",
      },
      {
        dataId: 232,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 137,
        size: "500.0 MB",
        validity: "1 month",
      },
      {
        dataId: 213,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 274,
        size: "1.0 GB",
        validity: "1 month",
      },
      {
        dataId: 214,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 548,
        size: "2.0 GB",
        validity: "1 month",
      },
      {
        dataId: 233,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 822,
        size: "3.0 GB",
        validity: "1 month",
      },
      {
        dataId: 216,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 1370,
        size: "5.0 GB",
        validity: "1 month",
      },
      {
        dataId: 257,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 3288,
        size: "12.0 GB",
        validity: "1 month",
      },
      {
        dataId: 217,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 2740,
        size: "10.0 GB",
        validity: "1 month",
      },
      {
        dataId: 243,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 4110,
        size: "15.0 GB",
        validity: "1 month",
      },
      {
        dataId: 258,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 5480,
        size: "20.0 GB",
        validity: "1 month",
      },
      {
        dataId: 259,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 10960,
        size: "40.0 GB",
        validity: "1 month",
      },
      {
        dataId: 260,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 20550,
        size: "75.0 GB",
        validity: "1 month",
      },
      {
        dataId: 261,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 27400,
        size: "100.0 GB",
        validity: "1 month",
      },

      // MTN DATA COUPONS
      {
        dataId: 344,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 225,
        size: "1.0 GB",
        validity: "1 day",
      },
      {
        dataId: 343,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 530,
        size: "3.5 GB",
        validity: "2 days",
      },
      {
        dataId: 333,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 2075,
        size: "15.0 GB",
        validity: "7 days",
      },
      {
        dataId: 334,
        network: "MTN",
        planType: "DATA COUPONS",
        amount: 112000000,
        size: "4.5 GB",
        validity: "1 month",
      },

      // AIRTEL SME
      {
        dataId: 358,
        network: "AIRTEL",
        planType: "SME",
        amount: 225,
        size: "1.0 GB",
        validity: "2 days",
      },
      {
        dataId: 359,
        network: "AIRTEL",
        planType: "SME",
        amount: 325,
        size: "2.0 GB",
        validity: "2 days",
      },
      {
        dataId: 360,
        network: "AIRTEL",
        planType: "SME",
        amount: 530,
        size: "3.0 GB",
        validity: "7 days",
      },
      {
        dataId: 361,
        network: "AIRTEL",
        planType: "SME",
        amount: 1030,
        size: "4.0 GB",
        validity: "30 days",
      },
      {
        dataId: 364,
        network: "AIRTEL",
        planType: "SME",
        amount: 1250,
        size: "5.0 GB",
        validity: "14 days",
      },
      {
        dataId: 362,
        network: "AIRTEL",
        planType: "SME",
        amount: 2050,
        size: "10.0 GB",
        validity: "30 days",
      },
      {
        dataId: 363,
        network: "AIRTEL",
        planType: "SME",
        amount: 3100,
        size: "15.0 GB",
        validity: "30 days",
      },

      // AIRTEL GIFTING
      {
        dataId: 336,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 125,
        size: "300.0 MB",
        validity: "2 days",
      },
      {
        dataId: 335,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 225,
        size: "1.0 GB",
        validity: "2 days",
      },
      {
        dataId: 337,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 325,
        size: "2.0 GB",
        validity: "2 days",
      },
      {
        dataId: 374,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 360,
        size: "1.5 GB",
        validity: "7 days",
      },
      {
        dataId: 375,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 360,
        size: "1.5 GB",
        validity: "7 days",
      },
      {
        dataId: 372,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 525,
        size: "2.0 GB",
        validity: "14 days",
      },
      {
        dataId: 338,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 530,
        size: "3.0 GB",
        validity: "7 days",
      },
      {
        dataId: 339,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 1030,
        size: "4.0 GB",
        validity: "30 days",
      },
      {
        dataId: 373,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 1250,
        size: "5.0 GB",
        validity: "14 days",
      },
      {
        dataId: 376,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 1660,
        size: "6.0 GB",
        validity: "30 days",
      },
      {
        dataId: 340,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 2050,
        size: "10.0 GB",
        validity: "30 days",
      },
      {
        dataId: 341,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 3100,
        size: "15.0 GB",
        validity: "30 days",
      },
      {
        dataId: 355,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 4100,
        size: "20.0 GB",
        validity: "30 days",
      },
      {
        dataId: 356,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 7100,
        size: "40.0 GB",
        validity: "30 days",
      },
      {
        dataId: 246,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 13375,
        size: "75.0 GB",
        validity: "1 month",
      },
      {
        dataId: 247,
        network: "AIRTEL",
        planType: "GIFTING",
        amount: 17600,
        size: "120.0 GB",
        validity: "1 month",
      },

      // AIRTEL CORPORATE GIFTING
      {
        dataId: 220,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 50,
        size: "100.0 MB",
        validity: "7 days",
      },
      {
        dataId: 221,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 100,
        size: "300.0 MB",
        validity: "7 days",
      },
      {
        dataId: 222,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 138,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 223,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 272,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 224,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 544,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 225,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 1360,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 280,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 2720,
        size: "10.0 GB",
        validity: "1 month",
      },
      {
        dataId: 294,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 4080,
        size: "15.0 GB",
        validity: "30 days",
      },
      {
        dataId: 295,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 5440,
        size: "20.0 GB",
        validity: "30 days",
      },

      // GLO SME
      {
        dataId: 366,
        network: "GLO",
        planType: "SME",
        amount: 195,
        size: "1.0 GB",
        validity: "1 day",
      },
      {
        dataId: 369,
        network: "GLO",
        planType: "SME",
        amount: 295,
        size: "2.0 GB",
        validity: "1 day",
      },
      {
        dataId: 370,
        network: "GLO",
        planType: "SME",
        amount: 485,
        size: "3.5 GB",
        validity: "2 days",
      },
      {
        dataId: 371,
        network: "GLO",
        planType: "SME",
        amount: 1950,
        size: "15.0 GB",
        validity: "7 days",
      },

      // GLO GIFTING
      {
        dataId: 350,
        network: "GLO",
        planType: "GIFTING",
        amount: 195,
        size: "1.0 GB",
        validity: "1 day",
      },
      {
        dataId: 351,
        network: "GLO",
        planType: "GIFTING",
        amount: 295,
        size: "2.0 GB",
        validity: "1 day",
      },
      {
        dataId: 352,
        network: "GLO",
        planType: "GIFTING",
        amount: 485,
        size: "3.5 GB",
        validity: "2 days",
      },
      {
        dataId: 354,
        network: "GLO",
        planType: "GIFTING",
        amount: 1950,
        size: "15.0 GB",
        validity: "7 days",
      },

      // GLO CORPORATE GIFTING
      {
        dataId: 291,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 55,
        size: "200.0 MB",
        validity: "30 days",
      },
      {
        dataId: 290,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 134,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 285,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 267,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 286,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 534,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 287,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 801,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 288,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 1335,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 289,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 2670,
        size: "10.0 GB",
        validity: "30 days",
      },

      // 9MOBILE SME
      {
        dataId: 248,
        network: "9MOBILE",
        planType: "SME",
        amount: 220,
        size: "1.0 GB",
        validity: "1 month",
      },
      {
        dataId: 249,
        network: "9MOBILE",
        planType: "SME",
        amount: 330,
        size: "1.5 GB",
        validity: "1 month",
      },
      {
        dataId: 250,
        network: "9MOBILE",
        planType: "SME",
        amount: 440,
        size: "2.0 GB",
        validity: "1 month",
      },
      {
        dataId: 251,
        network: "9MOBILE",
        planType: "SME",
        amount: 660,
        size: "3.0 GB",
        validity: "1 month",
      },
      {
        dataId: 252,
        network: "9MOBILE",
        planType: "SME",
        amount: 880,
        size: "4.0 GB",
        validity: "1 month",
      },
      {
        dataId: 253,
        network: "9MOBILE",
        planType: "SME",
        amount: 1100,
        size: "5.0 GB",
        validity: "1 month",
      },
      {
        dataId: 292,
        network: "9MOBILE",
        planType: "SME",
        amount: 2200,
        size: "10.0 GB",
        validity: "30 days",
      },
      {
        dataId: 304,
        network: "9MOBILE",
        planType: "SME",
        amount: 980,
        size: "4.5 GB",
        validity: "30 days",
      },

      // 9MOBILE GIFTING
      {
        dataId: 269,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 46,
        size: "25.0 MB",
        validity: "1 day",
      },
      {
        dataId: 270,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 175,
        size: "650.0 MB",
        validity: "1 day",
      },
      {
        dataId: 182,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 425,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 183,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 850,
        size: "1.5 GB",
        validity: "30 days",
      },
      {
        dataId: 184,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1020,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 185,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1275,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 186,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1700,
        size: "4.5 GB",
        validity: "30 days",
      },
      {
        dataId: 187,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 3400,
        size: "11.0 GB",
        validity: "30 days",
      },
      {
        dataId: 188,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 4200,
        size: "15.0 GB",
        validity: "30 days",
      },
      {
        dataId: 189,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 8500,
        size: "40.0 GB",
        validity: "30 days",
      },
      {
        dataId: 262,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 12750,
        size: "75.0 GB",
        validity: "1 month",
      },
      {
        dataId: 272,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 425,
        size: "2000.0 MB",
        validity: "3 days",
      },
      {
        dataId: 273,
        network: "9MOBILE",
        planType: "GIFTING",
        amount: 1275,
        size: "7.0 GB",
        validity: "7 days",
      },

      // 9MOBILE CORPORATE GIFTING
      {
        dataId: 305,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 30,
        size: "25.0 MB",
        validity: "30 days",
      },
      {
        dataId: 302,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 70,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 296,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 129,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 298,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 195,
        size: "1.5 GB",
        validity: "30 days",
      },
      {
        dataId: 297,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 258,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 299,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 387,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 303,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 516,
        size: "4.0 GB",
        validity: "30 days",
      },
      {
        dataId: 300,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 645,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 301,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 1290,
        size: "10.0 GB",
        validity: "30 days",
      },
    ].map((plan) => ({ ...plan, providerId: alrahuzdata.id })),
  });

  // Add data plans for dataplus
  await prisma.dataPlan.createMany({
    data: [
      {
        dataId: 296,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 25,
        size: "50.0 MB",
        validity: "30 days",
      },
      {
        dataId: 297,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 60,
        size: "150.0 MB",
        validity: "30 days",
      },
      {
        dataId: 295,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 70,
        size: "250.0 MB",
        validity: "30 days",
      },
      {
        dataId: 264,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 139,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 212,
        network: "MTN",
        planType: "SME",
        amount: 130,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 309,
        network: "MTN",
        planType: "SME2",
        amount: 132,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 248,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 275,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 207,
        network: "MTN",
        planType: "SME",
        amount: 258,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 304,
        network: "MTN",
        planType: "SME2",
        amount: 258,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 250,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 550,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 208,
        network: "MTN",
        planType: "SME",
        amount: 516,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 305,
        network: "MTN",
        planType: "SME2",
        amount: 516,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 266,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 825,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 209,
        network: "MTN",
        planType: "SME",
        amount: 774,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 306,
        network: "MTN",
        planType: "SME2",
        amount: 774,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 265,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 1375,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 210,
        network: "MTN",
        planType: "SME",
        amount: 1290,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 307,
        network: "MTN",
        planType: "SME2",
        amount: 1290,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 263,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 4090,
        size: "15.0 GB",
        validity: "30 days",
      },
      {
        dataId: 262,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 5500,
        size: "20.0 GB",
        validity: "30 days",
      },
      {
        dataId: 261,
        network: "MTN",
        planType: "CORPORATE GIFTING",
        amount: 6875,
        size: "25.0 GB",
        validity: "30 days (CG)",
      },
      {
        dataId: 221,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 55,
        size: "100.0 MB",
        validity: "7 days",
      },
      {
        dataId: 245,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 85,
        size: "300.0 MB",
        validity: "7 days",
      },
      {
        dataId: 246,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 136,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 213,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 272,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 214,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 544,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 328,
        network: "AIRTEL",
        planType: "AWOOF DATA",
        amount: 580,
        size: "3.0 GB",
        validity: "7 days (Don't buy if owing)",
      },
      {
        dataId: 215,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 1360,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 333,
        network: "AIRTEL",
        planType: "AWOOF DATA",
        amount: 1250,
        size: "5.0 GB",
        validity: "14 days (Don't buy if owing)",
      },
      {
        dataId: 216,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 2720,
        size: "10.0 GB",
        validity: "30 days",
      },
      {
        dataId: 334,
        network: "AIRTEL",
        planType: "AWOOF DATA",
        amount: 2300,
        size: "10.0 GB",
        validity: "30 days (Don't buy if owing)",
      },
      {
        dataId: 220,
        network: "AIRTEL",
        planType: "CORPORATE GIFTING",
        amount: 5440,
        size: "20.0 GB",
        validity: "30 days",
      },
      {
        dataId: 232,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 135,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 288,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 68,
        size: "200.0 MB",
        validity: "30 days",
      },
      {
        dataId: 233,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 265,
        size: "1.024 GB",
        validity: "30 days",
      },
      {
        dataId: 289,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 530,
        size: "2.048 GB",
        validity: "30 days",
      },
      {
        dataId: 284,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 795,
        size: "3.072 GB",
        validity: "30 days",
      },
      {
        dataId: 287,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 1325,
        size: "5.12 GB",
        validity: "30 days",
      },
      {
        dataId: 285,
        network: "GLO",
        planType: "CORPORATE GIFTING",
        amount: 2650,
        size: "10.24 GB",
        validity: "30 days",
      },
      {
        dataId: 227,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 130,
        size: "1.0 GB",
        validity: "30 days",
      },
      {
        dataId: 292,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 68,
        size: "500.0 MB",
        validity: "30 days",
      },
      {
        dataId: 293,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 55,
        size: "300.0 MB",
        validity: "30 days",
      },
      {
        dataId: 294,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 35,
        size: "100.0 MB",
        validity: "30 days",
      },
      {
        dataId: 278,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 260,
        size: "2.0 GB",
        validity: "30 days",
      },
      {
        dataId: 320,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 195,
        size: "1.5 GB",
        validity: "30 days",
      },
      {
        dataId: 322,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 520,
        size: "4.0 GB",
        validity: "30 days",
      },
      {
        dataId: 282,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 390,
        size: "3.0 GB",
        validity: "30 days",
      },
      {
        dataId: 279,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 650,
        size: "5.0 GB",
        validity: "30 days",
      },
      {
        dataId: 283,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 1950,
        size: "15.0 GB",
        validity: "30 days",
      },
      {
        dataId: 291,
        network: "9MOBILE",
        planType: "CORPORATE GIFTING",
        amount: 2600,
        size: "20.0 GB",
        validity: "30 days",
      },
    ].map((plan) => ({ ...plan, providerId: dataplus.id })),
  });
}

main()
  .then(() => console.log("Data plans added successfully"))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
