import {
  Antenna,
  CreditCard,
  Dollar,
  Fund,
  Home,
  Id,
  Modem,
  Notification,
  Phone,
  Receipt,
  Settings,
  Transaction,
  User,
  Verified,
  Wallet,
} from "../assets/icons";
import * as imgs from "./images";
export * from "./logos";
export * from "./images";

export const landingPageLinks = [
  {
    name: "Home",
    path: "home",
  },
  {
    name: "Features",
    path: "features",
  },
  {
    name: "About Us",
    path: "about-us",
  },
  {
    name: "Our Services",
    path: "our-services",
  },
  {
    name: "Our Clients",
    path: "our-clients",
  },
  {
    name: "FAQs",
    path: "faqs",
  },
];

export const features = [
  // {
  //   name: "Secured",
  //   description:
  //     "Advanced security protocols protect your transactions, ensuring that your data and payments are safeguarded from unauthorized access.",
  //   image: secure3d,
  // },
  {
    name: "Client Focused",
    description:
      "We prioritize your needs with dedicated support and resources designed to make your experience smooth and worry-free.",
    image: imgs.customerSupport,
  },
  {
    name: "Innovative and Automated",
    description:
      "Our automated solutions simplify complex processes, leveraging innovation to provide a seamless and efficient user experience.",
    image: imgs.auto3d,
  },
  {
    name: "Trustworthy",
    description:
      "With a strong commitment to reliability and transparency, we aim to build lasting trust with our clients in every interaction.",
    image: imgs.reliable3d,
  },
];

export const services = [
  {
    name: "Airtime Top-Up",
    description:
      "Instantly recharge your mobile with airtime across all networks.",
    Icon: Phone,
  },
  {
    name: "Data Subscription",
    description:
      "Subscribe to data plans with ease for uninterrupted internet access.",
    Icon: Antenna,
  },
  {
    name: "Utility Bill Payment",
    description: "Pay your electricity and water bills securely and on time.",
    Icon: Receipt,
  },
  {
    name: "Cable TV Subscription",
    description:
      "Renew your GOTV or DSTV subscription quickly and conveniently.",
    Icon: Modem,
  },
  {
    name: "NIN and BVN Verification",
    description:
      "Verify your National Identification Number (NIN), Bank Verification Number (BVN) details and print slips.",
    Icon: Id,
  },
];

export const clients = [
  {
    name: "John Doe",
    review:
      "MyAmtApp makes paying bills and recharging so easy! It’s reliable and super fast. Highly recommend!",
    Icon: User,
    starRating: 3,
  },
  {
    name: "Jane Smith",
    review:
      "Excellent service! I can handle all my subscriptions and verifications in one place. A real time-saver.",
    Icon: User,
    starRating: 4,
  },
  {
    name: "Samuel Lee",
    review:
      "The security features give me peace of mind. It’s a trustworthy app for all my transactions.",
    Icon: User,
    starRating: 5,
  },
];

export const faqs = [
  {
    question: "What is MyAmtApp?",
    answer:
      "MyAmtApp is a virtual top-up platform that allows you to buy airtime, data, pay utility bills, and handle essential verifications all in one secure app.",
  },
  {
    question: "How do I top up airtime using MyAmtApp?",
    answer:
      "Simply select 'Airtime Top-Up,' choose your network, enter the amount, and confirm your payment. The airtime will be instantly credited to the chosen number.",
  },
  {
    question: "Is MyAmtApp secure?",
    answer:
      "Yes, MyAmtApp uses advanced security protocols to ensure all transactions and personal data are protected.",
  },
  {
    question: "Can I pay my electricity and cable bills with MyAmtApp?",
    answer:
      "Absolutely! MyAmtApp allows you to pay for utilities like electricity (NEPA bills) and renew cable subscriptions for providers like GOTV and DSTV.",
  },
  {
    question: "How do I verify my NIN or BVN using MyAmtApp?",
    answer:
      "Go to the 'Verifications' section, select NIN or BVN verification, and follow the prompts to complete the process. You can also print the verification slip if needed.",
  },
  {
    question: "What payment methods does MyAmtApp accept?",
    answer:
      "MyAmtApp accepts various payment methods, including debit cards and mobile wallets, to make your transactions as convenient as possible.",
  },
  {
    question: "How do I contact customer support?",
    answer:
      "You can reach customer support through the 'Help' section in the app or via our contact information on the website.",
  },
];

export const footerLinks = [
  {
    heading: "Company",
    links: [
      { name: "About Us", path: "/about" },
      { name: "Careers", path: "/careers" },
      { name: "Blog", path: "/blog" },
      { name: "Press", path: "/press" },
    ],
  },
  {
    heading: "Support",
    links: [
      { name: "Help Center", path: "/help" },
      { name: "Contact Us", path: "/contact" },
      { name: "FAQs", path: "/faqs" },
      { name: "Privacy Policy", path: "/privacy-policy" },
      { name: "Terms of Service", path: "/terms" },
    ],
  },
  {
    heading: "Services",
    links: [
      { name: "Airtime Top-Up", path: "/services/airtime-topup" },
      { name: "Data Subscription", path: "/services/data-subscription" },
      { name: "Bill Payment", path: "/services/bill-payment" },
      { name: "Verifications", path: "/services/verifications" },
    ],
  },
  {
    heading: "Follow Us",
    links: [
      { name: "Facebook", path: "https://facebook.com/MyAmtApp" },
      { name: "Twitter", path: "https://twitter.com/MyAmtApp" },
      { name: "Instagram", path: "https://instagram.com/MyAmtApp" },
      { name: "LinkedIn", path: "https://linkedin.com/company/MyAmtApp" },
    ],
  },
];

export const sidebarLinks = [
  { name: "Dashboard", path: "/dashboard", Icon: Home },
  { name: "Buy Data", path: "/buy-data", Icon: Antenna },
  { name: "Buy Airtime", path: "/buy-airtime", Icon: Phone },
  { name: "Electricity Bill", path: "/electricity-bill", Icon: Dollar },
  { name: "Cable Subscription", path: "/cable-subscription", Icon: Modem },
  {
    name: "Verifications",
    path: "/verifications",
    Icon: Verified,
    childLinks: [
      { name: "NIN Verification", path: "/verifications/nin" },
      { name: "NIN With Phone", path: "/verifications/nin-with-phone" },
      { name: "BVN Verification", path: "/verifications/bvn" },
    ],
  },
  { name: "Fund Wallet", path: "/fund-wallet", Icon: Wallet },
  {
    name: "Transactions",
    path: "/transactions-history",
    Icon: Transaction,
  },
  { name: "Notifications", path: "/notifications", Icon: Notification },
  { name: "Settings", path: "/account-settings", Icon: Settings },
];

export const userStatsData = [
  {
    label: "Wallet Balance",
    value: 1000,
    Icon: Wallet,
  },
  {
    label: "Total Funding",
    value: 1000,
    Icon: Fund,
  },
  {
    label: "Total Spent",
    value: 1000,
    Icon: CreditCard,
  },
];

export const ninSlips = [
  {
    name: "Information",
    img: imgs.ninInformation,
    price: 150,
  },
  {
    name: "Regular",
    img: imgs.ninRegular,
    price: 200,
  },
  {
    name: "Standard",
    img: imgs.ninStandard,
    price: 250,
  },
  {
    name: "Premium",
    img: imgs.ninPremium,
    price: 300,
  },
];

export const bvnSlipDetails = [
  { id: 1, name: "basic", title: "Basic Details", price: 150 },

  { id: 2, name: "advanced", title: "Advanced Details", price: 150 },
];

export const dataTypes = [
  {
    name: "anwardataco",
    MTN: ["SME", "GIFTING"],
    GLO: ["SME", "CORPORATE GIFTING"],
    AIRTEL: ["SME", "CORPORATE GIFTING"],
    "9MOBILE": ["GIFTING", "CORPORATE GIFTING"],
  },
  {
    name: "alrahuzdata",
    MTN: [
      "SME",
      "SME2",
      "GIFTING",
      "CORPORATE GIFTING",
      "DATA COUPONS",
      "DATA SHARE",
    ],
    GLO: ["SME", "GIFTING", "CORPORATE GIFTING"],
    AIRTEL: ["SME", "GIFTING", "CORPORATE GIFTING"],
    "9MOBILE": ["SME", "GIFTING", "CORPORATE GIFTING"],
  },
  {
    name: "dataplus",
    MTN: ["SME", "CORPORATE GIFTING"],
    GLO: ["CORPORATE GIFTING", "AWOOF DATA"],
    AIRTEL: ["SME", "SME2", "CORPORATE GIFTING", "AWOOF DATA"],
    "9MOBILE": ["CORPORATE GIFTING"],
  },
  {
    name: "ameentaccetelecom",
    MTN: ["SME", "SME2", "GIFTING", "DIRECT-COUPON"],
    GLO: ["CORPORATE-GIFTING"],
    AIRTEL: ["CORPORATE-GIFTING"],
    "9MOBILE": ["CORPORATE-GIFTING"],
  },
];

export const dataTypess = [
  "SME",
  "SME 2",
  "GIFTING",
  "CORPORATE GIFTING",
  "DATA COUPONS",
  "DATA SHARE",
  "AWOOF DATA",
];

export const dataPlans = {
  anwardataco: [
    // MTN SME
    {
      data_id: 225,
      network: "MTN",
      plan_type: "SME",
      amount: 129,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 7,
      network: "MTN",
      plan_type: "SME",
      amount: 259,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 8,
      network: "MTN",
      plan_type: "SME",
      amount: 520,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 44,
      network: "MTN",
      plan_type: "SME",
      amount: 777,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 11,
      network: "MTN",
      plan_type: "SME",
      amount: 1295,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 224,
      network: "MTN",
      plan_type: "SME",
      amount: 2590,
      size: "10.0 GB",
      validity: "30 days",
    },

    // MTN SME 2
    {
      data_id: 277,
      network: "MTN",
      plan_type: "SME 2",
      amount: 130,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 263,
      network: "MTN",
      plan_type: "SME 2",
      amount: 260,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 269,
      network: "MTN",
      plan_type: "SME 2",
      amount: 512,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 268,
      network: "MTN",
      plan_type: "SME 2",
      amount: 780,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 308,
      network: "MTN",
      plan_type: "SME 2",
      amount: 390,
      size: "1.5 GB",
      validity: "30 days",
    },
    {
      data_id: 267,
      network: "MTN",
      plan_type: "SME 2",
      amount: 1280,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 307,
      network: "MTN",
      plan_type: "SME 2",
      amount: 1040,
      size: "4.0 GB",
      validity: "30 days",
    },
    {
      data_id: 266,
      network: "MTN",
      plan_type: "SME 2",
      amount: 2600,
      size: "10.0 GB",
      validity: "30 days",
    },

    // MTN GIFTING
    {
      data_id: 306,
      network: "MTN",
      plan_type: "GIFTING",
      amount: 125,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 301,
      network: "MTN",
      plan_type: "GIFTING",
      amount: 250,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 302,
      network: "MTN",
      plan_type: "GIFTING",
      amount: 500,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 303,
      network: "MTN",
      plan_type: "GIFTING",
      amount: 750,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 304,
      network: "MTN",
      plan_type: "GIFTING",
      amount: 1300,
      size: "5.0 GB",
      validity: "30 days",
    },

    // MTN CORPORATE GIFTING
    {
      data_id: 218,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 132,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 213,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 265,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 214,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 530,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 215,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 795,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 216,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 1325,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 217,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 2650,
      size: "10.0 GB",
      validity: "30 days",
    },
    {
      data_id: 220,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 3975,
      size: "15.0 GB",
      validity: "30 days",
    },
    {
      data_id: 287,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 5200,
      size: "20.0 GB",
      validity: "30 days",
    },
    {
      data_id: 242,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 87,
      size: "250.0 MB",
      validity: "30 days",
    },
    {
      data_id: 243,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 67,
      size: "150.0 MB",
      validity: "30 days",
    },
    {
      data_id: 244,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 37,
      size: "50.0 MB",
      validity: "30 days",
    },

    // MTN DATA COUPONS
    {
      data_id: 299,
      network: "MTN",
      plan_type: "DATA COUPONS",
      amount: 248,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 296,
      network: "MTN",
      plan_type: "DATA COUPONS",
      amount: 493,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 309,
      network: "MTN",
      plan_type: "DATA COUPONS",
      amount: 738,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 310,
      network: "MTN",
      plan_type: "DATA COUPONS",
      amount: 1228,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 311,
      network: "MTN",
      plan_type: "DATA COUPONS",
      amount: 125,
      size: "500.0 MB",
      validity: "30 days",
    },

    // AIRTEL CORPORATE GIFTING
    {
      data_id: 226,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 50,
      size: "100.0 MB",
      validity: "7 days",
    },
    {
      data_id: 228,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 140,
      size: "500.0 MB",
      validity: "14 days",
    },
    {
      data_id: 229,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 280,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 230,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 560,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 231,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 1400,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 238,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 4200,
      size: "15.0 GB",
      validity: "30 days",
    },
    {
      data_id: 239,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 5600,
      size: "20.0 GB",
      validity: "30 days",
    },
    {
      data_id: 314,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 85,
      size: "300.0 MB",
      validity: "30 days",
    },
    {
      data_id: 313,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 2750,
      size: "10.0 GB",
      validity: "30 days",
    },

    // GLO GIFTING
    {
      data_id: 194,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 475,
      size: "1.05 GB",
      validity: "14 days",
    },
    {
      data_id: 195,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 960,
      size: "2.5 GB",
      validity: "30 days",
    },
    {
      data_id: 196,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 1420,
      size: "4.1 GB",
      validity: "30 days",
    },
    {
      data_id: 198,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 1890,
      size: "7.7 GB",
      validity: "30 days",
    },
    {
      data_id: 199,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 2700,
      size: "10.0 GB",
      validity: "30 days",
    },
    {
      data_id: 200,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 2820,
      size: "13.25 GB",
      validity: "30 days",
    },
    {
      data_id: 201,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 4230,
      size: "18.25 GB",
      validity: "30 days",
    },
    {
      data_id: 202,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 6750,
      size: "29.5 GB",
      validity: "30 days",
    },
    {
      data_id: 203,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 8430,
      size: "50.0 GB",
      validity: "30 days",
    },
    {
      data_id: 204,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 13050,
      size: "93.0 GB",
      validity: "30 days",
    },
    {
      data_id: 205,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 16200,
      size: "119.0 GB",
      validity: "30 days",
    },
    {
      data_id: 206,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 18000,
      size: "138.0 GB",
      validity: "30 days",
    },

    // GLO CORPORATE GIFTING
    {
      data_id: 246,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 1325,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 247,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 132,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 248,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 530,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 249,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 53,
      size: "200.0 MB",
      validity: "14 days",
    },
    {
      data_id: 250,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 265,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 251,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 2650,
      size: "10.0 GB",
      validity: "30 days",
    },
    {
      data_id: 252,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 795,
      size: "3.0 GB",
      validity: "30 days",
    },

    // 9MOBILE GIFTING
    {
      data_id: 183,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 890,
      size: "1.5 GB",
      validity: "30 days",
    },
    {
      data_id: 184,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 1060,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 185,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 1340,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 186,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 1770,
      size: "4.5 GB",
      validity: "30 days",
    },
    {
      data_id: 187,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 3540,
      size: "11.0 GB",
      validity: "30 days",
    },
    {
      data_id: 188,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 2550,
      size: "15.0 GB",
      validity: "30 days",
    },
    {
      data_id: 189,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 8840,
      size: "40.0 GB",
      validity: "30 days",
    },
    {
      data_id: 190,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 12330,
      size: "75.0 GB",
      validity: "30 days",
    },

    // 9MOBILE CORPORATE GIFTING
    {
      data_id: 271,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 170,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 256,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 120,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 258,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 340,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 259,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 255,
      size: "1.5 GB",
      validity: "30 days",
    },
    {
      data_id: 260,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 510,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 261,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 850,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 262,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 1700,
      size: "10.0 GB",
      validity: "30 days",
    },
    {
      data_id: 270,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 680,
      size: "4.0 GB",
      validity: "30 days",
    },
    {
      data_id: 281,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 85,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 282,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 40,
      size: "100.0 MB",
      validity: "30 days",
    },
    {
      data_id: 283,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 30,
      size: "25.0 MB",
      validity: "30 days",
    },
    {
      data_id: 284,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 20,
      size: "15.0 MB",
      validity: "30 days",
    },
    {
      data_id: 286,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 3400,
      size: "20.0 GB",
      validity: "30 days",
    },
  ],
  alrahuzdata: [
    // MTN SME
    {
      data_id: 219,
      network: "MTN",
      plan_type: "SME",
      amount: 129,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 7,
      network: "MTN",
      plan_type: "SME",
      amount: 258,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 8,
      network: "MTN",
      plan_type: "SME",
      amount: 516,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 44,
      network: "MTN",
      plan_type: "SME",
      amount: 774,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 11,
      network: "MTN",
      plan_type: "SME",
      amount: 1290,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 226,
      network: "MTN",
      plan_type: "SME",
      amount: 2580,
      size: "10.0 GB",
      validity: "30 days",
    },

    // MTN SME 2
    {
      data_id: 307,
      network: "MTN",
      plan_type: "SME 2",
      amount: 15,
      size: "50.0 MB",
      validity: "7 days",
    },
    {
      data_id: 312,
      network: "MTN",
      plan_type: "SME 2",
      amount: 20,
      size: "20.0 MB",
      validity: "1 month",
    },
    {
      data_id: 311,
      network: "MTN",
      plan_type: "SME 2",
      amount: 24,
      size: "25.0 MB",
      validity: "1 month",
    },
    {
      data_id: 313,
      network: "MTN",
      plan_type: "SME 2",
      amount: 65,
      size: "100.0 MB",
      validity: "1 month",
    },
    {
      data_id: 306,
      network: "MTN",
      plan_type: "SME 2",
      amount: 134,
      size: "500.0 MB",
      validity: "1 month",
    },
    {
      data_id: 319,
      network: "MTN",
      plan_type: "SME 2",
      amount: 268,
      size: "1.0 GB",
      validity: "1 month",
    },
    {
      data_id: 314,
      network: "MTN",
      plan_type: "SME 2",
      amount: 402,
      size: "1.5 GB",
      validity: "1 month",
    },
    {
      data_id: 318,
      network: "MTN",
      plan_type: "SME 2",
      amount: 536,
      size: "2.0 GB",
      validity: "1 month",
    },
    {
      data_id: 317,
      network: "MTN",
      plan_type: "SME 2",
      amount: 804,
      size: "3.0 GB",
      validity: "1 month",
    },
    {
      data_id: 320,
      network: "MTN",
      plan_type: "SME 2",
      amount: 1072,
      size: "4.0 GB",
      validity: "1 month",
    },
    {
      data_id: 316,
      network: "MTN",
      plan_type: "SME 2",
      amount: 1340,
      size: "5.0 GB",
      validity: "1 month",
    },
    {
      data_id: 309,
      network: "MTN",
      plan_type: "SME 2",
      amount: 1608,
      size: "6.0 GB",
      validity: "1 month",
    },
    {
      data_id: 308,
      network: "MTN",
      plan_type: "SME 2",
      amount: 1876,
      size: "7.0 GB",
      validity: "1 month",
    },
    {
      data_id: 315,
      network: "MTN",
      plan_type: "SME 2",
      amount: 2680,
      size: "10.0 GB",
      validity: "1 month",
    },

    // MTN GIFTING
    {
      data_id: 377,
      network: "MTN",
      plan_type: "GIFTING",
      amount: 220,
      size: "1.0 GB",
      validity: "1 day",
    },
    {
      data_id: 378,
      network: "MTN",
      plan_type: "GIFTING",
      amount: 520,
      size: "3.5 GB",
      validity: "2 days",
    },
    {
      data_id: 379,
      network: "MTN",
      plan_type: "GIFTING",
      amount: 2040,
      size: "15.0 GB",
      validity: "7 days",
    },

    // MTN CORPORATE GIFTING
    {
      data_id: 254,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 20,
      size: "50.0 MB",
      validity: "1 month",
    },
    {
      data_id: 255,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 55,
      size: "150.0 MB",
      validity: "1 month",
    },
    {
      data_id: 256,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 70,
      size: "250.0 MB",
      validity: "1 month",
    },
    {
      data_id: 232,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 137,
      size: "500.0 MB",
      validity: "1 month",
    },
    {
      data_id: 213,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 274,
      size: "1.0 GB",
      validity: "1 month",
    },
    {
      data_id: 214,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 548,
      size: "2.0 GB",
      validity: "1 month",
    },
    {
      data_id: 233,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 822,
      size: "3.0 GB",
      validity: "1 month",
    },
    {
      data_id: 216,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 1370,
      size: "5.0 GB",
      validity: "1 month",
    },
    {
      data_id: 257,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 3288,
      size: "12.0 GB",
      validity: "1 month",
    },
    {
      data_id: 217,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 2740,
      size: "10.0 GB",
      validity: "1 month",
    },
    {
      data_id: 243,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 4110,
      size: "15.0 GB",
      validity: "1 month",
    },
    {
      data_id: 258,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 5480,
      size: "20.0 GB",
      validity: "1 month",
    },
    {
      data_id: 259,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 10960,
      size: "40.0 GB",
      validity: "1 month",
    },
    {
      data_id: 260,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 20550,
      size: "75.0 GB",
      validity: "1 month",
    },
    {
      data_id: 261,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 27400,
      size: "100.0 GB",
      validity: "1 month",
    },

    // MTN DATA COUPONS
    {
      data_id: 344,
      network: "MTN",
      plan_type: "DATA COUPONS",
      amount: 225,
      size: "1.0 GB",
      validity: "1 day",
    },
    {
      data_id: 343,
      network: "MTN",
      plan_type: "DATA COUPONS",
      amount: 530,
      size: "3.5 GB",
      validity: "2 days",
    },
    {
      data_id: 333,
      network: "MTN",
      plan_type: "DATA COUPONS",
      amount: 2075,
      size: "15.0 GB",
      validity: "7 days",
    },
    {
      data_id: 334,
      network: "MTN",
      plan_type: "DATA COUPONS",
      amount: 112000000,
      size: "4.5 GB",
      validity: "1 month",
    },

    // AIRTEL SME
    {
      data_id: 358,
      network: "AIRTEL",
      plan_type: "SME",
      amount: 225,
      size: "1.0 GB",
      validity: "2 days",
    },
    {
      data_id: 359,
      network: "AIRTEL",
      plan_type: "SME",
      amount: 325,
      size: "2.0 GB",
      validity: "2 days",
    },
    {
      data_id: 360,
      network: "AIRTEL",
      plan_type: "SME",
      amount: 530,
      size: "3.0 GB",
      validity: "7 days",
    },
    {
      data_id: 361,
      network: "AIRTEL",
      plan_type: "SME",
      amount: 1030,
      size: "4.0 GB",
      validity: "30 days",
    },
    {
      data_id: 364,
      network: "AIRTEL",
      plan_type: "SME",
      amount: 1250,
      size: "5.0 GB",
      validity: "14 days",
    },
    {
      data_id: 362,
      network: "AIRTEL",
      plan_type: "SME",
      amount: 2050,
      size: "10.0 GB",
      validity: "30 days",
    },
    {
      data_id: 363,
      network: "AIRTEL",
      plan_type: "SME",
      amount: 3100,
      size: "15.0 GB",
      validity: "30 days",
    },

    // AIRTEL GIFTING
    {
      data_id: 336,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 125,
      size: "300.0 MB",
      validity: "2 days",
    },
    {
      data_id: 335,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 225,
      size: "1.0 GB",
      validity: "2 days",
    },
    {
      data_id: 337,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 325,
      size: "2.0 GB",
      validity: "2 days",
    },
    {
      data_id: 374,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 360,
      size: "1.5 GB",
      validity: "7 days",
    },
    {
      data_id: 375,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 360,
      size: "1.5 GB",
      validity: "7 days",
    },
    {
      data_id: 372,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 525,
      size: "2.0 GB",
      validity: "14 days",
    },
    {
      data_id: 338,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 530,
      size: "3.0 GB",
      validity: "7 days",
    },
    {
      data_id: 339,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 1030,
      size: "4.0 GB",
      validity: "30 days",
    },
    {
      data_id: 373,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 1250,
      size: "5.0 GB",
      validity: "14 days",
    },
    {
      data_id: 376,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 1660,
      size: "6.0 GB",
      validity: "30 days",
    },
    {
      data_id: 340,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 2050,
      size: "10.0 GB",
      validity: "30 days",
    },
    {
      data_id: 341,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 3100,
      size: "15.0 GB",
      validity: "30 days",
    },
    {
      data_id: 355,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 4100,
      size: "20.0 GB",
      validity: "30 days",
    },
    {
      data_id: 356,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 7100,
      size: "40.0 GB",
      validity: "30 days",
    },
    {
      data_id: 246,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 13375,
      size: "75.0 GB",
      validity: "1 month",
    },
    {
      data_id: 247,
      network: "AIRTEL",
      plan_type: "GIFTING",
      amount: 17600,
      size: "120.0 GB",
      validity: "1 month",
    },

    // AIRTEL CORPORATE GIFTING
    {
      data_id: 220,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 50,
      size: "100.0 MB",
      validity: "7 days",
    },
    {
      data_id: 221,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 100,
      size: "300.0 MB",
      validity: "7 days",
    },
    {
      data_id: 222,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 138,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 223,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 272,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 224,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 544,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 225,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 1360,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 280,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 2720,
      size: "10.0 GB",
      validity: "1 month",
    },
    {
      data_id: 294,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 4080,
      size: "15.0 GB",
      validity: "30 days",
    },
    {
      data_id: 295,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 5440,
      size: "20.0 GB",
      validity: "30 days",
    },

    // GLO SME
    {
      data_id: 366,
      network: "GLO",
      plan_type: "SME",
      amount: 195,
      size: "1.0 GB",
      validity: "1 day",
    },
    {
      data_id: 369,
      network: "GLO",
      plan_type: "SME",
      amount: 295,
      size: "2.0 GB",
      validity: "1 day",
    },
    {
      data_id: 370,
      network: "GLO",
      plan_type: "SME",
      amount: 485,
      size: "3.5 GB",
      validity: "2 days",
    },
    {
      data_id: 371,
      network: "GLO",
      plan_type: "SME",
      amount: 1950,
      size: "15.0 GB",
      validity: "7 days",
    },

    // GLO GIFTING
    {
      data_id: 350,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 195,
      size: "1.0 GB",
      validity: "1 day",
    },
    {
      data_id: 351,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 295,
      size: "2.0 GB",
      validity: "1 day",
    },
    {
      data_id: 352,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 485,
      size: "3.5 GB",
      validity: "2 days",
    },
    {
      data_id: 354,
      network: "GLO",
      plan_type: "GIFTING",
      amount: 1950,
      size: "15.0 GB",
      validity: "7 days",
    },

    // GLO CORPORATE GIFTING
    {
      data_id: 291,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 55,
      size: "200.0 MB",
      validity: "30 days",
    },
    {
      data_id: 290,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 134,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 285,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 267,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 286,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 534,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 287,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 801,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 288,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 1335,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 289,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 2670,
      size: "10.0 GB",
      validity: "30 days",
    },

    // 9MOBILE SME
    {
      data_id: 248,
      network: "9MOBILE",
      plan_type: "SME",
      amount: 220,
      size: "1.0 GB",
      validity: "1 month",
    },
    {
      data_id: 249,
      network: "9MOBILE",
      plan_type: "SME",
      amount: 330,
      size: "1.5 GB",
      validity: "1 month",
    },
    {
      data_id: 250,
      network: "9MOBILE",
      plan_type: "SME",
      amount: 440,
      size: "2.0 GB",
      validity: "1 month",
    },
    {
      data_id: 251,
      network: "9MOBILE",
      plan_type: "SME",
      amount: 660,
      size: "3.0 GB",
      validity: "1 month",
    },
    {
      data_id: 252,
      network: "9MOBILE",
      plan_type: "SME",
      amount: 880,
      size: "4.0 GB",
      validity: "1 month",
    },
    {
      data_id: 253,
      network: "9MOBILE",
      plan_type: "SME",
      amount: 1100,
      size: "5.0 GB",
      validity: "1 month",
    },
    {
      data_id: 292,
      network: "9MOBILE",
      plan_type: "SME",
      amount: 2200,
      size: "10.0 GB",
      validity: "30 days",
    },
    {
      data_id: 304,
      network: "9MOBILE",
      plan_type: "SME",
      amount: 980,
      size: "4.5 GB",
      validity: "30 days",
    },

    // 9MOBILE GIFTING
    {
      data_id: 269,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 46,
      size: "25.0 MB",
      validity: "1 day",
    },
    {
      data_id: 270,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 175,
      size: "650.0 MB",
      validity: "1 day",
    },
    {
      data_id: 182,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 425,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 183,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 850,
      size: "1.5 GB",
      validity: "30 days",
    },
    {
      data_id: 184,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 1020,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 185,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 1275,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 186,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 1700,
      size: "4.5 GB",
      validity: "30 days",
    },
    {
      data_id: 187,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 3400,
      size: "11.0 GB",
      validity: "30 days",
    },
    {
      data_id: 188,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 4200,
      size: "15.0 GB",
      validity: "30 days",
    },
    {
      data_id: 189,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 8500,
      size: "40.0 GB",
      validity: "30 days",
    },
    {
      data_id: 262,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 12750,
      size: "75.0 GB",
      validity: "1 month",
    },
    {
      data_id: 272,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 425,
      size: "2000.0 MB",
      validity: "3 days",
    },
    {
      data_id: 273,
      network: "9MOBILE",
      plan_type: "GIFTING",
      amount: 1275,
      size: "7.0 GB",
      validity: "7 days",
    },

    // 9MOBILE CORPORATE GIFTING
    {
      data_id: 305,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 30,
      size: "25.0 MB",
      validity: "30 days",
    },
    {
      data_id: 302,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 70,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 296,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 129,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 298,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 195,
      size: "1.5 GB",
      validity: "30 days",
    },
    {
      data_id: 297,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 258,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 299,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 387,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 303,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 516,
      size: "4.0 GB",
      validity: "30 days",
    },
    {
      data_id: 300,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 645,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 301,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 1290,
      size: "10.0 GB",
      validity: "30 days",
    },
  ],
  dataplus: [
    {
      data_id: 296,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 25,
      size: "50.0 MB",
      validity: "30 days",
    },
    {
      data_id: 297,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 60,
      size: "150.0 MB",
      validity: "30 days",
    },
    {
      data_id: 295,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 70,
      size: "250.0 MB",
      validity: "30 days",
    },
    {
      data_id: 264,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 139,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 212,
      network: "MTN",
      plan_type: "SME",
      amount: 130,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 309,
      network: "MTN",
      plan_type: "SME2",
      amount: 132,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 248,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 275,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 207,
      network: "MTN",
      plan_type: "SME",
      amount: 258,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 304,
      network: "MTN",
      plan_type: "SME2",
      amount: 258,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 250,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 550,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 208,
      network: "MTN",
      plan_type: "SME",
      amount: 516,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 305,
      network: "MTN",
      plan_type: "SME2",
      amount: 516,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 266,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 825,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 209,
      network: "MTN",
      plan_type: "SME",
      amount: 774,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 306,
      network: "MTN",
      plan_type: "SME2",
      amount: 774,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 265,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 1375,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 210,
      network: "MTN",
      plan_type: "SME",
      amount: 1290,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 307,
      network: "MTN",
      plan_type: "SME2",
      amount: 1290,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 263,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 4090,
      size: "15.0 GB",
      validity: "30 days",
    },
    {
      data_id: 262,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 5500,
      size: "20.0 GB",
      validity: "30 days",
    },
    {
      data_id: 261,
      network: "MTN",
      plan_type: "CORPORATE GIFTING",
      amount: 6875,
      size: "25.0 GB",
      validity: "30 days (CG)",
    },
    {
      data_id: 221,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 55,
      size: "100.0 MB",
      validity: "7 days",
    },
    {
      data_id: 245,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 85,
      size: "300.0 MB",
      validity: "7 days",
    },
    {
      data_id: 246,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 136,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 213,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 272,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 214,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 544,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 328,
      network: "AIRTEL",
      plan_type: "AWOOF DATA",
      amount: 580,
      size: "3.0 GB",
      validity: "7 days (Don't buy if owing)",
    },
    {
      data_id: 215,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 1360,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 333,
      network: "AIRTEL",
      plan_type: "AWOOF DATA",
      amount: 1250,
      size: "5.0 GB",
      validity: "14 days (Don't buy if owing)",
    },
    {
      data_id: 216,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 2720,
      size: "10.0 GB",
      validity: "30 days",
    },
    {
      data_id: 334,
      network: "AIRTEL",
      plan_type: "AWOOF DATA",
      amount: 2300,
      size: "10.0 GB",
      validity: "30 days (Don't buy if owing)",
    },
    {
      data_id: 220,
      network: "AIRTEL",
      plan_type: "CORPORATE GIFTING",
      amount: 5440,
      size: "20.0 GB",
      validity: "30 days",
    },
    {
      data_id: 232,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 135,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 288,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 68,
      size: "200.0 MB",
      validity: "30 days",
    },
    {
      data_id: 233,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 265,
      size: "1.024 GB",
      validity: "30 days",
    },
    {
      data_id: 289,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 530,
      size: "2.048 GB",
      validity: "30 days",
    },
    {
      data_id: 284,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 795,
      size: "3.072 GB",
      validity: "30 days",
    },
    {
      data_id: 287,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 1325,
      size: "5.12 GB",
      validity: "30 days",
    },
    {
      data_id: 285,
      network: "GLO",
      plan_type: "CORPORATE GIFTING",
      amount: 2650,
      size: "10.24 GB",
      validity: "30 days",
    },
    {
      data_id: 227,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 130,
      size: "1.0 GB",
      validity: "30 days",
    },
    {
      data_id: 292,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 68,
      size: "500.0 MB",
      validity: "30 days",
    },
    {
      data_id: 293,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 55,
      size: "300.0 MB",
      validity: "30 days",
    },
    {
      data_id: 294,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 35,
      size: "100.0 MB",
      validity: "30 days",
    },
    {
      data_id: 278,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 260,
      size: "2.0 GB",
      validity: "30 days",
    },
    {
      data_id: 320,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 195,
      size: "1.5 GB",
      validity: "30 days",
    },
    {
      data_id: 322,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 520,
      size: "4.0 GB",
      validity: "30 days",
    },
    {
      data_id: 282,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 390,
      size: "3.0 GB",
      validity: "30 days",
    },
    {
      data_id: 279,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 650,
      size: "5.0 GB",
      validity: "30 days",
    },
    {
      data_id: 283,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 1950,
      size: "15.0 GB",
      validity: "30 days",
    },
    {
      data_id: 291,
      network: "9MOBILE",
      plan_type: "CORPORATE GIFTING",
      amount: 2600,
      size: "20.0 GB",
      validity: "30 days",
    },
  ],
};

export const anwardatacoDataPlans = [
  // MTN SME
  {
    data_id: 225,
    network: "MTN",
    plan_type: "SME",
    amount: 129,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 7,
    network: "MTN",
    plan_type: "SME",
    amount: 259,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 8,
    network: "MTN",
    plan_type: "SME",
    amount: 520,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 44,
    network: "MTN",
    plan_type: "SME",
    amount: 777,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 11,
    network: "MTN",
    plan_type: "SME",
    amount: 1295,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 224,
    network: "MTN",
    plan_type: "SME",
    amount: 2590,
    size: "10.0 GB",
    validity: "30 days",
  },

  // MTN SME 2
  {
    data_id: 277,
    network: "MTN",
    plan_type: "SME 2",
    amount: 130,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 263,
    network: "MTN",
    plan_type: "SME 2",
    amount: 260,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 269,
    network: "MTN",
    plan_type: "SME 2",
    amount: 512,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 268,
    network: "MTN",
    plan_type: "SME 2",
    amount: 780,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 308,
    network: "MTN",
    plan_type: "SME 2",
    amount: 390,
    size: "1.5 GB",
    validity: "30 days",
  },
  {
    data_id: 267,
    network: "MTN",
    plan_type: "SME 2",
    amount: 1280,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 307,
    network: "MTN",
    plan_type: "SME 2",
    amount: 1040,
    size: "4.0 GB",
    validity: "30 days",
  },
  {
    data_id: 266,
    network: "MTN",
    plan_type: "SME 2",
    amount: 2600,
    size: "10.0 GB",
    validity: "30 days",
  },

  // MTN GIFTING
  {
    data_id: 306,
    network: "MTN",
    plan_type: "GIFTING",
    amount: 125,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 301,
    network: "MTN",
    plan_type: "GIFTING",
    amount: 250,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 302,
    network: "MTN",
    plan_type: "GIFTING",
    amount: 500,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 303,
    network: "MTN",
    plan_type: "GIFTING",
    amount: 750,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 304,
    network: "MTN",
    plan_type: "GIFTING",
    amount: 1300,
    size: "5.0 GB",
    validity: "30 days",
  },

  // MTN CORPORATE GIFTING
  {
    data_id: 218,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 132,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 213,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 265,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 214,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 530,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 215,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 795,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 216,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 1325,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 217,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 2650,
    size: "10.0 GB",
    validity: "30 days",
  },
  {
    data_id: 220,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 3975,
    size: "15.0 GB",
    validity: "30 days",
  },
  {
    data_id: 287,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 5200,
    size: "20.0 GB",
    validity: "30 days",
  },
  {
    data_id: 242,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 87,
    size: "250.0 MB",
    validity: "30 days",
  },
  {
    data_id: 243,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 67,
    size: "150.0 MB",
    validity: "30 days",
  },
  {
    data_id: 244,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 37,
    size: "50.0 MB",
    validity: "30 days",
  },

  // MTN DATA COUPONS
  {
    data_id: 299,
    network: "MTN",
    plan_type: "DATA COUPONS",
    amount: 248,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 296,
    network: "MTN",
    plan_type: "DATA COUPONS",
    amount: 493,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 309,
    network: "MTN",
    plan_type: "DATA COUPONS",
    amount: 738,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 310,
    network: "MTN",
    plan_type: "DATA COUPONS",
    amount: 1228,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 311,
    network: "MTN",
    plan_type: "DATA COUPONS",
    amount: 125,
    size: "500.0 MB",
    validity: "30 days",
  },

  // AIRTEL CORPORATE GIFTING
  {
    data_id: 226,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 50,
    size: "100.0 MB",
    validity: "7 days",
  },
  {
    data_id: 228,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 140,
    size: "500.0 MB",
    validity: "14 days",
  },
  {
    data_id: 229,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 280,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 230,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 560,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 231,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 1400,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 238,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 4200,
    size: "15.0 GB",
    validity: "30 days",
  },
  {
    data_id: 239,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 5600,
    size: "20.0 GB",
    validity: "30 days",
  },
  {
    data_id: 314,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 85,
    size: "300.0 MB",
    validity: "30 days",
  },
  {
    data_id: 313,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 2750,
    size: "10.0 GB",
    validity: "30 days",
  },

  // GLO GIFTING
  {
    data_id: 194,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 475,
    size: "1.05 GB",
    validity: "14 days",
  },
  {
    data_id: 195,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 960,
    size: "2.5 GB",
    validity: "30 days",
  },
  {
    data_id: 196,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 1420,
    size: "4.1 GB",
    validity: "30 days",
  },
  {
    data_id: 198,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 1890,
    size: "7.7 GB",
    validity: "30 days",
  },
  {
    data_id: 199,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 2700,
    size: "10.0 GB",
    validity: "30 days",
  },
  {
    data_id: 200,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 2820,
    size: "13.25 GB",
    validity: "30 days",
  },
  {
    data_id: 201,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 4230,
    size: "18.25 GB",
    validity: "30 days",
  },
  {
    data_id: 202,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 6750,
    size: "29.5 GB",
    validity: "30 days",
  },
  {
    data_id: 203,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 8430,
    size: "50.0 GB",
    validity: "30 days",
  },
  {
    data_id: 204,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 13050,
    size: "93.0 GB",
    validity: "30 days",
  },
  {
    data_id: 205,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 16200,
    size: "119.0 GB",
    validity: "30 days",
  },
  {
    data_id: 206,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 18000,
    size: "138.0 GB",
    validity: "30 days",
  },

  // GLO CORPORATE GIFTING
  {
    data_id: 246,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 1325,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 247,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 132,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 248,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 530,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 249,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 53,
    size: "200.0 MB",
    validity: "14 days",
  },
  {
    data_id: 250,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 265,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 251,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 2650,
    size: "10.0 GB",
    validity: "30 days",
  },
  {
    data_id: 252,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 795,
    size: "3.0 GB",
    validity: "30 days",
  },

  // 9MOBILE GIFTING
  {
    data_id: 183,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 890,
    size: "1.5 GB",
    validity: "30 days",
  },
  {
    data_id: 184,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 1060,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 185,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 1340,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 186,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 1770,
    size: "4.5 GB",
    validity: "30 days",
  },
  {
    data_id: 187,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 3540,
    size: "11.0 GB",
    validity: "30 days",
  },
  {
    data_id: 188,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 2550,
    size: "15.0 GB",
    validity: "30 days",
  },
  {
    data_id: 189,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 8840,
    size: "40.0 GB",
    validity: "30 days",
  },
  {
    data_id: 190,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 12330,
    size: "75.0 GB",
    validity: "30 days",
  },

  // 9MOBILE CORPORATE GIFTING
  {
    data_id: 271,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 170,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 256,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 120,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 258,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 340,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 259,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 255,
    size: "1.5 GB",
    validity: "30 days",
  },
  {
    data_id: 260,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 510,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 261,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 850,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 262,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 1700,
    size: "10.0 GB",
    validity: "30 days",
  },
  {
    data_id: 270,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 680,
    size: "4.0 GB",
    validity: "30 days",
  },
  {
    data_id: 281,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 85,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 282,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 40,
    size: "100.0 MB",
    validity: "30 days",
  },
  {
    data_id: 283,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 30,
    size: "25.0 MB",
    validity: "30 days",
  },
  {
    data_id: 284,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 20,
    size: "15.0 MB",
    validity: "30 days",
  },
  {
    data_id: 286,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 3400,
    size: "20.0 GB",
    validity: "30 days",
  },
];

export const alrahuzdataDataPlans = [
  // MTN SME
  {
    data_id: 219,
    network: "MTN",
    plan_type: "SME",
    amount: 129,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 7,
    network: "MTN",
    plan_type: "SME",
    amount: 258,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 8,
    network: "MTN",
    plan_type: "SME",
    amount: 516,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 44,
    network: "MTN",
    plan_type: "SME",
    amount: 774,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 11,
    network: "MTN",
    plan_type: "SME",
    amount: 1290,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 226,
    network: "MTN",
    plan_type: "SME",
    amount: 2580,
    size: "10.0 GB",
    validity: "30 days",
  },

  // MTN SME 2
  {
    data_id: 307,
    network: "MTN",
    plan_type: "SME 2",
    amount: 15,
    size: "50.0 MB",
    validity: "7 days",
  },
  {
    data_id: 312,
    network: "MTN",
    plan_type: "SME 2",
    amount: 20,
    size: "20.0 MB",
    validity: "1 month",
  },
  {
    data_id: 311,
    network: "MTN",
    plan_type: "SME 2",
    amount: 24,
    size: "25.0 MB",
    validity: "1 month",
  },
  {
    data_id: 313,
    network: "MTN",
    plan_type: "SME 2",
    amount: 65,
    size: "100.0 MB",
    validity: "1 month",
  },
  {
    data_id: 306,
    network: "MTN",
    plan_type: "SME 2",
    amount: 134,
    size: "500.0 MB",
    validity: "1 month",
  },
  {
    data_id: 319,
    network: "MTN",
    plan_type: "SME 2",
    amount: 268,
    size: "1.0 GB",
    validity: "1 month",
  },
  {
    data_id: 314,
    network: "MTN",
    plan_type: "SME 2",
    amount: 402,
    size: "1.5 GB",
    validity: "1 month",
  },
  {
    data_id: 318,
    network: "MTN",
    plan_type: "SME 2",
    amount: 536,
    size: "2.0 GB",
    validity: "1 month",
  },
  {
    data_id: 317,
    network: "MTN",
    plan_type: "SME 2",
    amount: 804,
    size: "3.0 GB",
    validity: "1 month",
  },
  {
    data_id: 320,
    network: "MTN",
    plan_type: "SME 2",
    amount: 1072,
    size: "4.0 GB",
    validity: "1 month",
  },
  {
    data_id: 316,
    network: "MTN",
    plan_type: "SME 2",
    amount: 1340,
    size: "5.0 GB",
    validity: "1 month",
  },
  {
    data_id: 309,
    network: "MTN",
    plan_type: "SME 2",
    amount: 1608,
    size: "6.0 GB",
    validity: "1 month",
  },
  {
    data_id: 308,
    network: "MTN",
    plan_type: "SME 2",
    amount: 1876,
    size: "7.0 GB",
    validity: "1 month",
  },
  {
    data_id: 315,
    network: "MTN",
    plan_type: "SME 2",
    amount: 2680,
    size: "10.0 GB",
    validity: "1 month",
  },

  // MTN GIFTING
  {
    data_id: 377,
    network: "MTN",
    plan_type: "GIFTING",
    amount: 220,
    size: "1.0 GB",
    validity: "1 day",
  },
  {
    data_id: 378,
    network: "MTN",
    plan_type: "GIFTING",
    amount: 520,
    size: "3.5 GB",
    validity: "2 days",
  },
  {
    data_id: 379,
    network: "MTN",
    plan_type: "GIFTING",
    amount: 2040,
    size: "15.0 GB",
    validity: "7 days",
  },

  // MTN CORPORATE GIFTING
  {
    data_id: 254,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 20,
    size: "50.0 MB",
    validity: "1 month",
  },
  {
    data_id: 255,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 55,
    size: "150.0 MB",
    validity: "1 month",
  },
  {
    data_id: 256,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 70,
    size: "250.0 MB",
    validity: "1 month",
  },
  {
    data_id: 232,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 137,
    size: "500.0 MB",
    validity: "1 month",
  },
  {
    data_id: 213,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 274,
    size: "1.0 GB",
    validity: "1 month",
  },
  {
    data_id: 214,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 548,
    size: "2.0 GB",
    validity: "1 month",
  },
  {
    data_id: 233,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 822,
    size: "3.0 GB",
    validity: "1 month",
  },
  {
    data_id: 216,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 1370,
    size: "5.0 GB",
    validity: "1 month",
  },
  {
    data_id: 257,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 3288,
    size: "12.0 GB",
    validity: "1 month",
  },
  {
    data_id: 217,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 2740,
    size: "10.0 GB",
    validity: "1 month",
  },
  {
    data_id: 243,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 4110,
    size: "15.0 GB",
    validity: "1 month",
  },
  {
    data_id: 258,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 5480,
    size: "20.0 GB",
    validity: "1 month",
  },
  {
    data_id: 259,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 10960,
    size: "40.0 GB",
    validity: "1 month",
  },
  {
    data_id: 260,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 20550,
    size: "75.0 GB",
    validity: "1 month",
  },
  {
    data_id: 261,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 27400,
    size: "100.0 GB",
    validity: "1 month",
  },

  // MTN DATA COUPONS
  {
    data_id: 344,
    network: "MTN",
    plan_type: "DATA COUPONS",
    amount: 225,
    size: "1.0 GB",
    validity: "1 day",
  },
  {
    data_id: 343,
    network: "MTN",
    plan_type: "DATA COUPONS",
    amount: 530,
    size: "3.5 GB",
    validity: "2 days",
  },
  {
    data_id: 333,
    network: "MTN",
    plan_type: "DATA COUPONS",
    amount: 2075,
    size: "15.0 GB",
    validity: "7 days",
  },
  {
    data_id: 334,
    network: "MTN",
    plan_type: "DATA COUPONS",
    amount: 112000000,
    size: "4.5 GB",
    validity: "1 month",
  },

  // AIRTEL SME
  {
    data_id: 358,
    network: "AIRTEL",
    plan_type: "SME",
    amount: 225,
    size: "1.0 GB",
    validity: "2 days",
  },
  {
    data_id: 359,
    network: "AIRTEL",
    plan_type: "SME",
    amount: 325,
    size: "2.0 GB",
    validity: "2 days",
  },
  {
    data_id: 360,
    network: "AIRTEL",
    plan_type: "SME",
    amount: 530,
    size: "3.0 GB",
    validity: "7 days",
  },
  {
    data_id: 361,
    network: "AIRTEL",
    plan_type: "SME",
    amount: 1030,
    size: "4.0 GB",
    validity: "30 days",
  },
  {
    data_id: 364,
    network: "AIRTEL",
    plan_type: "SME",
    amount: 1250,
    size: "5.0 GB",
    validity: "14 days",
  },
  {
    data_id: 362,
    network: "AIRTEL",
    plan_type: "SME",
    amount: 2050,
    size: "10.0 GB",
    validity: "30 days",
  },
  {
    data_id: 363,
    network: "AIRTEL",
    plan_type: "SME",
    amount: 3100,
    size: "15.0 GB",
    validity: "30 days",
  },

  // AIRTEL GIFTING
  {
    data_id: 336,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 125,
    size: "300.0 MB",
    validity: "2 days",
  },
  {
    data_id: 335,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 225,
    size: "1.0 GB",
    validity: "2 days",
  },
  {
    data_id: 337,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 325,
    size: "2.0 GB",
    validity: "2 days",
  },
  {
    data_id: 374,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 360,
    size: "1.5 GB",
    validity: "7 days",
  },
  {
    data_id: 375,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 360,
    size: "1.5 GB",
    validity: "7 days",
  },
  {
    data_id: 372,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 525,
    size: "2.0 GB",
    validity: "14 days",
  },
  {
    data_id: 338,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 530,
    size: "3.0 GB",
    validity: "7 days",
  },
  {
    data_id: 339,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 1030,
    size: "4.0 GB",
    validity: "30 days",
  },
  {
    data_id: 373,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 1250,
    size: "5.0 GB",
    validity: "14 days",
  },
  {
    data_id: 376,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 1660,
    size: "6.0 GB",
    validity: "30 days",
  },
  {
    data_id: 340,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 2050,
    size: "10.0 GB",
    validity: "30 days",
  },
  {
    data_id: 341,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 3100,
    size: "15.0 GB",
    validity: "30 days",
  },
  {
    data_id: 355,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 4100,
    size: "20.0 GB",
    validity: "30 days",
  },
  {
    data_id: 356,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 7100,
    size: "40.0 GB",
    validity: "30 days",
  },
  {
    data_id: 246,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 13375,
    size: "75.0 GB",
    validity: "1 month",
  },
  {
    data_id: 247,
    network: "AIRTEL",
    plan_type: "GIFTING",
    amount: 17600,
    size: "120.0 GB",
    validity: "1 month",
  },

  // AIRTEL CORPORATE GIFTING
  {
    data_id: 220,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 50,
    size: "100.0 MB",
    validity: "7 days",
  },
  {
    data_id: 221,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 100,
    size: "300.0 MB",
    validity: "7 days",
  },
  {
    data_id: 222,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 138,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 223,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 272,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 224,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 544,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 225,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 1360,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 280,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 2720,
    size: "10.0 GB",
    validity: "1 month",
  },
  {
    data_id: 294,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 4080,
    size: "15.0 GB",
    validity: "30 days",
  },
  {
    data_id: 295,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 5440,
    size: "20.0 GB",
    validity: "30 days",
  },

  // GLO SME
  {
    data_id: 366,
    network: "GLO",
    plan_type: "SME",
    amount: 195,
    size: "1.0 GB",
    validity: "1 day",
  },
  {
    data_id: 369,
    network: "GLO",
    plan_type: "SME",
    amount: 295,
    size: "2.0 GB",
    validity: "1 day",
  },
  {
    data_id: 370,
    network: "GLO",
    plan_type: "SME",
    amount: 485,
    size: "3.5 GB",
    validity: "2 days",
  },
  {
    data_id: 371,
    network: "GLO",
    plan_type: "SME",
    amount: 1950,
    size: "15.0 GB",
    validity: "7 days",
  },

  // GLO GIFTING
  {
    data_id: 350,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 195,
    size: "1.0 GB",
    validity: "1 day",
  },
  {
    data_id: 351,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 295,
    size: "2.0 GB",
    validity: "1 day",
  },
  {
    data_id: 352,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 485,
    size: "3.5 GB",
    validity: "2 days",
  },
  {
    data_id: 354,
    network: "GLO",
    plan_type: "GIFTING",
    amount: 1950,
    size: "15.0 GB",
    validity: "7 days",
  },

  // GLO CORPORATE GIFTING
  {
    data_id: 291,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 55,
    size: "200.0 MB",
    validity: "30 days",
  },
  {
    data_id: 290,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 134,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 285,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 267,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 286,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 534,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 287,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 801,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 288,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 1335,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 289,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 2670,
    size: "10.0 GB",
    validity: "30 days",
  },

  // 9MOBILE SME
  {
    data_id: 248,
    network: "9MOBILE",
    plan_type: "SME",
    amount: 220,
    size: "1.0 GB",
    validity: "1 month",
  },
  {
    data_id: 249,
    network: "9MOBILE",
    plan_type: "SME",
    amount: 330,
    size: "1.5 GB",
    validity: "1 month",
  },
  {
    data_id: 250,
    network: "9MOBILE",
    plan_type: "SME",
    amount: 440,
    size: "2.0 GB",
    validity: "1 month",
  },
  {
    data_id: 251,
    network: "9MOBILE",
    plan_type: "SME",
    amount: 660,
    size: "3.0 GB",
    validity: "1 month",
  },
  {
    data_id: 252,
    network: "9MOBILE",
    plan_type: "SME",
    amount: 880,
    size: "4.0 GB",
    validity: "1 month",
  },
  {
    data_id: 253,
    network: "9MOBILE",
    plan_type: "SME",
    amount: 1100,
    size: "5.0 GB",
    validity: "1 month",
  },
  {
    data_id: 292,
    network: "9MOBILE",
    plan_type: "SME",
    amount: 2200,
    size: "10.0 GB",
    validity: "30 days",
  },
  {
    data_id: 304,
    network: "9MOBILE",
    plan_type: "SME",
    amount: 980,
    size: "4.5 GB",
    validity: "30 days",
  },

  // 9MOBILE GIFTING
  {
    data_id: 269,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 46,
    size: "25.0 MB",
    validity: "1 day",
  },
  {
    data_id: 270,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 175,
    size: "650.0 MB",
    validity: "1 day",
  },
  {
    data_id: 182,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 425,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 183,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 850,
    size: "1.5 GB",
    validity: "30 days",
  },
  {
    data_id: 184,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 1020,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 185,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 1275,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 186,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 1700,
    size: "4.5 GB",
    validity: "30 days",
  },
  {
    data_id: 187,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 3400,
    size: "11.0 GB",
    validity: "30 days",
  },
  {
    data_id: 188,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 4200,
    size: "15.0 GB",
    validity: "30 days",
  },
  {
    data_id: 189,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 8500,
    size: "40.0 GB",
    validity: "30 days",
  },
  {
    data_id: 262,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 12750,
    size: "75.0 GB",
    validity: "1 month",
  },
  {
    data_id: 272,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 425,
    size: "2000.0 MB",
    validity: "3 days",
  },
  {
    data_id: 273,
    network: "9MOBILE",
    plan_type: "GIFTING",
    amount: 1275,
    size: "7.0 GB",
    validity: "7 days",
  },

  // 9MOBILE CORPORATE GIFTING
  {
    data_id: 305,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 30,
    size: "25.0 MB",
    validity: "30 days",
  },
  {
    data_id: 302,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 70,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 296,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 129,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 298,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 195,
    size: "1.5 GB",
    validity: "30 days",
  },
  {
    data_id: 297,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 258,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 299,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 387,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 303,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 516,
    size: "4.0 GB",
    validity: "30 days",
  },
  {
    data_id: 300,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 645,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 301,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 1290,
    size: "10.0 GB",
    validity: "30 days",
  },
];

export const dataplusDataPlans = [
  {
    data_id: 296,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 25,
    size: "50.0 MB",
    validity: "30 days",
  },
  {
    data_id: 297,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 60,
    size: "150.0 MB",
    validity: "30 days",
  },
  {
    data_id: 295,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 70,
    size: "250.0 MB",
    validity: "30 days",
  },
  {
    data_id: 264,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 139,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 212,
    network: "MTN",
    plan_type: "SME",
    amount: 130,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 309,
    network: "MTN",
    plan_type: "SME2",
    amount: 132,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 248,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 275,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 207,
    network: "MTN",
    plan_type: "SME",
    amount: 258,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 304,
    network: "MTN",
    plan_type: "SME2",
    amount: 258,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 250,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 550,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 208,
    network: "MTN",
    plan_type: "SME",
    amount: 516,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 305,
    network: "MTN",
    plan_type: "SME2",
    amount: 516,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 266,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 825,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 209,
    network: "MTN",
    plan_type: "SME",
    amount: 774,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 306,
    network: "MTN",
    plan_type: "SME2",
    amount: 774,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 265,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 1375,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 210,
    network: "MTN",
    plan_type: "SME",
    amount: 1290,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 307,
    network: "MTN",
    plan_type: "SME2",
    amount: 1290,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 263,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 4090,
    size: "15.0 GB",
    validity: "30 days",
  },
  {
    data_id: 262,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 5500,
    size: "20.0 GB",
    validity: "30 days",
  },
  {
    data_id: 261,
    network: "MTN",
    plan_type: "CORPORATE GIFTING",
    amount: 6875,
    size: "25.0 GB",
    validity: "30 days (CG)",
  },
  {
    data_id: 221,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 55,
    size: "100.0 MB",
    validity: "7 days",
  },
  {
    data_id: 245,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 85,
    size: "300.0 MB",
    validity: "7 days",
  },
  {
    data_id: 246,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 136,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 213,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 272,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 214,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 544,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 328,
    network: "AIRTEL",
    plan_type: "AWOOF DATA",
    amount: 580,
    size: "3.0 GB",
    validity: "7 days (Don't buy if owing)",
  },
  {
    data_id: 215,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 1360,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 333,
    network: "AIRTEL",
    plan_type: "AWOOF DATA",
    amount: 1250,
    size: "5.0 GB",
    validity: "14 days (Don't buy if owing)",
  },
  {
    data_id: 216,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 2720,
    size: "10.0 GB",
    validity: "30 days",
  },
  {
    data_id: 334,
    network: "AIRTEL",
    plan_type: "AWOOF DATA",
    amount: 2300,
    size: "10.0 GB",
    validity: "30 days (Don't buy if owing)",
  },
  {
    data_id: 220,
    network: "AIRTEL",
    plan_type: "CORPORATE GIFTING",
    amount: 5440,
    size: "20.0 GB",
    validity: "30 days",
  },
  {
    data_id: 232,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 135,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 288,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 68,
    size: "200.0 MB",
    validity: "30 days",
  },
  {
    data_id: 233,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 265,
    size: "1.024 GB",
    validity: "30 days",
  },
  {
    data_id: 289,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 530,
    size: "2.048 GB",
    validity: "30 days",
  },
  {
    data_id: 284,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 795,
    size: "3.072 GB",
    validity: "30 days",
  },
  {
    data_id: 287,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 1325,
    size: "5.12 GB",
    validity: "30 days",
  },
  {
    data_id: 285,
    network: "GLO",
    plan_type: "CORPORATE GIFTING",
    amount: 2650,
    size: "10.24 GB",
    validity: "30 days",
  },
  {
    data_id: 227,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 130,
    size: "1.0 GB",
    validity: "30 days",
  },
  {
    data_id: 292,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 68,
    size: "500.0 MB",
    validity: "30 days",
  },
  {
    data_id: 293,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 55,
    size: "300.0 MB",
    validity: "30 days",
  },
  {
    data_id: 294,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 35,
    size: "100.0 MB",
    validity: "30 days",
  },
  {
    data_id: 278,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 260,
    size: "2.0 GB",
    validity: "30 days",
  },
  {
    data_id: 320,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 195,
    size: "1.5 GB",
    validity: "30 days",
  },
  {
    data_id: 322,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 520,
    size: "4.0 GB",
    validity: "30 days",
  },
  {
    data_id: 282,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 390,
    size: "3.0 GB",
    validity: "30 days",
  },
  {
    data_id: 279,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 650,
    size: "5.0 GB",
    validity: "30 days",
  },
  {
    data_id: 283,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 1950,
    size: "15.0 GB",
    validity: "30 days",
  },
  {
    data_id: 291,
    network: "9MOBILE",
    plan_type: "CORPORATE GIFTING",
    amount: 2600,
    size: "20.0 GB",
    validity: "30 days",
  },
];

export const anwardatacoCablePlans = [
  { plan_id: 18, plan_name: "GOtv Smallie", amount: 1575 },
  { plan_id: 34, plan_name: "GOtv Smallie - Monthly", amount: 1575 },
  { plan_id: 16, plan_name: "GOtv Jinja", amount: 3300 },
  { plan_id: 17, plan_name: "GOtv Jolli", amount: 4850 },
  { plan_id: 2, plan_name: "GOtv Max", amount: 7200 },
  { plan_id: 35, plan_name: "GOtv Smallie - Quarterly", amount: 4172 },
  { plan_id: 36, plan_name: "GOtv Smallie - Yearly", amount: 12300 },
  { plan_id: 47, plan_name: "GOtv Supa monthly", amount: 15700 },
  { plan_id: 21, plan_name: "DStv Great Wall Standalone", amount: 1725 },
  { plan_id: 20, plan_name: "DStv Padi", amount: 3600 },
  { plan_id: 6, plan_name: "DStv Yanga", amount: 5100 },
  { plan_id: 26, plan_name: "DStv Confam + ExtraView", amount: 8200 },
  { plan_id: 27, plan_name: "DStv Yanga + ExtraView", amount: 8200 },
  { plan_id: 19, plan_name: "DStv Confam", amount: 9300 },
  { plan_id: 23, plan_name: "DStv Asia", amount: 7100 },
  { plan_id: 7, plan_name: "DStv Compact", amount: 15700 },
  { plan_id: 29, plan_name: "DStv Compact + Extra View", amount: 16500 },
  { plan_id: 31, plan_name: "DStv Compact Plus - Extra View", amount: 17150 },
  { plan_id: 8, plan_name: "DStv Compact Plus", amount: 25000 },
  { plan_id: 30, plan_name: "DStv Premium + Extra View", amount: 33500 },
  { plan_id: 25, plan_name: "DStv Premium Asia", amount: 33000 },
  { plan_id: 9, plan_name: "DStv Premium", amount: 37000 },
  { plan_id: 24, plan_name: "DStv Premium French", amount: 45600 },
  { plan_id: 5, plan_name: "DStv Asian Bouqet", amount: 24250 },
  { plan_id: 32, plan_name: "DStv HDPVR Access Service", amount: 2900 },
  { plan_id: 28, plan_name: "DStv Padi + ExtraView", amount: 6950 },
  { plan_id: 37, plan_name: "Startime Nova - 600 Naira - 1 Week", amount: 600 },
  { plan_id: 10, plan_name: "Startime NOVA", amount: 1700 },
  {
    plan_id: 14,
    plan_name: "Startime Nova - 1700Naira - 1 Month",
    amount: 1700,
  },
  {
    plan_id: 40,
    plan_name: "Startime Classic - 1700Naira - 1 Week",
    amount: 1700,
  },
  {
    plan_id: 12,
    plan_name: "Startime Basic - 3300Naira - 1 Month",
    amount: 3300,
  },
  {
    plan_id: 38,
    plan_name: "Startime Basic - 1100 Naira - 1 Week",
    amount: 1100,
  },
  {
    plan_id: 39,
    plan_name: "Startime Smart - 1300Naira - 1 Week",
    amount: 1300,
  },
  {
    plan_id: 13,
    plan_name: "Startime Smart - 3800Naira - 1 Month",
    amount: 3800,
  },
  { plan_id: 33, plan_name: "Startime ExtraView Access", amount: 4000 },
  {
    plan_id: 11,
    plan_name: "Startime Classic - 5000Naira - 1 Month",
    amount: 5000,
  },
  {
    plan_id: 15,
    plan_name: "Startime Super - 7000 Naira - 1 Month",
    amount: 7000,
  },
  {
    plan_id: 41,
    plan_name: "Startime Super - 2700Naira - 1 Week",
    amount: 2700,
  },
];

export const alrahuzdataCablePlans = [
  { plan_id: 34, plan_name: "GOtv Smallie - Monthly", amount: 1575 },
  { plan_id: 37, plan_name: "Nova - 600 Naira - 1 Week", amount: 600 },
  { plan_id: 38, plan_name: "Basic - 1250 Naira - 1 Week", amount: 1250 },
  { plan_id: 39, plan_name: "Smart - 1550 Naira - 1 Week", amount: 1550 },
  { plan_id: 16, plan_name: "GOtv Jinja", amount: 3300 },
  { plan_id: 17, plan_name: "GOtv Jolli", amount: 4850 },
  { plan_id: 2, plan_name: "GOtv Max", amount: 7200 },
  { plan_id: 47, plan_name: "GOTv SUPA", amount: 9600 },
  { plan_id: 49, plan_name: "GOTv SUPA PLUS", amount: 15700 },
  { plan_id: 35, plan_name: "GOtv Smallie - Quarterly", amount: 4175 },
  { plan_id: 36, plan_name: "GOtv Smallie - Yearly", amount: 12300 },
  { plan_id: 6, plan_name: "DStv Yanga", amount: 5100 },
  { plan_id: 20, plan_name: "DStv Padi", amount: 2950 },
  { plan_id: 19, plan_name: "DStv Confam", amount: 9300 },
  { plan_id: 26, plan_name: "DStv Confam + ExtraView", amount: 14300 },
  { plan_id: 27, plan_name: "DStv Yanga + ExtraView", amount: 10100 },
  { plan_id: 28, plan_name: "DStv Padi + ExtraView", amount: 8600 },
  { plan_id: 7, plan_name: "DStv Compact", amount: 15700 },
  { plan_id: 29, plan_name: "DStv Compact + Extra View", amount: 20700 },
  { plan_id: 8, plan_name: "DStv Compact Plus", amount: 25000 },
  { plan_id: 31, plan_name: "DStv Compact Plus - Extra View", amount: 37400 },
  { plan_id: 9, plan_name: "DStv Premium", amount: 37000 },
  { plan_id: 30, plan_name: "DStv Premium + Extra View", amount: 42000 },
  { plan_id: 23, plan_name: "DStv Asia", amount: 12400 },
  { plan_id: 24, plan_name: "DStv Premium French", amount: 57500 },
  { plan_id: 25, plan_name: "DStv Premium Asia", amount: 42000 },
  { plan_id: 33, plan_name: "DStv ExtraView Access", amount: 5000 },
  {
    plan_id: 11,
    plan_name: "Startime Classic - 5500 Naira - 1 Mont",
    amount: 5500,
  },
  {
    plan_id: 12,
    plan_name: "Startime Basic - 3700 Naira - 1 Month",
    amount: 3700,
  },
  {
    plan_id: 13,
    plan_name: "Startime Smart - 4700 Naira - 1 Month",
    amount: 4700,
  },
  {
    plan_id: 14,
    plan_name: "Startime Nova - 1900 Naira - 1 Month",
    amount: 1900,
  },
  {
    plan_id: 15,
    plan_name: "Startime Super - 9000 Naira - 1 Month",
    amount: 9000,
  },
  {
    plan_id: 48,
    plan_name: "Startime Super - 9000 Naira - 1 Month",
    amount: 9000,
  },
  {
    plan_id: 40,
    plan_name: "Startime Classic - 1900 Naira - 1 Week",
    amount: 1900,
  },
  {
    plan_id: 41,
    plan_name: "Startime Super - 3000 Naira - 1 Week",
    amount: 3000,
  },
];

export const dataplusCablePlans = [
  { plan_id: 34, plan_name: "GOtv Smallie - Monthly", amount: 1575 },
  { plan_id: 35, plan_name: "GOtv Smallie - Quarterly", amount: 4175 },
  { plan_id: 36, plan_name: "GOtv Smallie - Yearly", amount: 12300 },
  { plan_id: 16, plan_name: "GOtv Jinja", amount: 3300 },
  { plan_id: 17, plan_name: "GOtv Jolli", amount: 4850 },
  { plan_id: 2, plan_name: "GOtv Max", amount: 7200 },
  { plan_id: 48, plan_name: "GOtv Supa", amount: 9600 },
  { plan_id: 20, plan_name: "DStv Padi", amount: 3600 },
  { plan_id: 6, plan_name: "DStv Yanga", amount: 5100 },
  { plan_id: 19, plan_name: "DStv Confam", amount: 9300 },
  { plan_id: 47, plan_name: "DStv Confam + ExtraView", amount: 14300 },
  { plan_id: 7, plan_name: "DStv Compact", amount: 15700 },
  { plan_id: 29, plan_name: "DStv Compact + Extra View", amount: 20700 },
  { plan_id: 31, plan_name: "DStv Compact Plus + Extra View", amount: 30000 },
  { plan_id: 8, plan_name: "DStv Compact Plus", amount: 25000 },
  { plan_id: 9, plan_name: "DStv Premium", amount: 37000 },
  { plan_id: 30, plan_name: "DStv Premium + Extra View", amount: 42000 },
  {
    plan_id: 11,
    plan_name: "Startime Classic - 5000 Naira - 1 Month",
    amount: 5000,
  },
  {
    plan_id: 12,
    plan_name: "Startime Basic - 3300 Naira - 1 Month",
    amount: 3300,
  },
  {
    plan_id: 13,
    plan_name: "Startime Smart - 4200 Naira - 1 Month",
    amount: 4200,
  },
  {
    plan_id: 14,
    plan_name: "Startime Nova - 1700 Naira - 1 Month",
    amount: 1700,
  },
  {
    plan_id: 15,
    plan_name: "Startime Super - 8200 Naira - 1 Month",
    amount: 8200,
  },
  {
    plan_id: 37,
    plan_name: "Startime Nova - 500 Naira - 1 Week (antenna)",
    amount: 500,
  },
  {
    plan_id: 49,
    plan_name: "Startime Nova - 600 Naira - 1 Week (Dish)",
    amount: 600,
  },
  {
    plan_id: 38,
    plan_name: "Startime Basic - 1400 Naira - 1 Week",
    amount: 1400,
  },
  {
    plan_id: 39,
    plan_name: "Startime Smart -1400 Naira - 1 Week",
    amount: 1400,
  },
  {
    plan_id: 40,
    plan_name: "Startime Classic - 2100 Naira - 1 Week",
    amount: 2100,
  },
  {
    plan_id: 41,
    plan_name: "Startime Super - 2800 Naira - 1 Week",
    amount: 2800,
  },
];
